### ISSUE TITLE
Infra Schema Documentation

### ISSUE THREAD

**Issue by christophe-blt** [bSI-InfraRoom/IFC-Specification#106]
There are no documentation on Schema : ifcRoad, ifcRail, IfcPortsAndWaterways and IfcSharedInfrastructureElements

Example with ifcRoad DocSchema. 
![image](https://user-images.githubusercontent.com/82803096/123924610-6c435b80-d98a-11eb-839e-b4a68cf54553.png)

**Comment by AlexBrad1eyCT** [comment]
moved to #122
