### ISSUE TITLE
Project breakdown and ownership

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#112]
Strict hierarchies are very rigid and a more flexible solution is required in infrastructure projects. Currently, the project breakdown is being used for various purposes such as local placement, containment, domain ownership etc. The concepts can be split and a more flexible project setup achieved.

Options:
1. Project breakdown with containers split from ownership retaining local placement
2. Split also location from containers to allow ownership and location be independent
3. ...

For IFC4x3 this was addressed in #111 but for a better solution additional test cases are required.

**Comment by TLiebich** [comment]
see a general proposal for solving the interference issue between spatial elements here - #111
