### ISSUE TITLE
[IFC Tunnel] Voxel geometric representation and data management

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#117]
A requirement from IFC Tunnel stakeholders is to have a representation based on voxels. Each voxel has to provide the ability to carry a physical characteristic in the form of a value or a directed value i.e. vector.

[DOCUMENTATION]
[Voxel representation.pdf](https://github.com/bSI-InfraRoom/IFC-Specification/files/6863942/Voxel.representation.pdf)

Initial feedback and derived issues:
#194 
#195 
#202 
TODO ... Adding some more feedback

**Comment by TLiebich** [comment]
assigned to IFC4.4 or IFC5 ?

**Comment by SergejMuhic** [comment]
Good question for which I do not know the answer. To my knowledge, IFC Tunnel is not waiting for IFC5.

**Comment by anborr** [comment]
We would require it as part of IFC4.4. But we need approval by SCTE.

**Comment by anborr** [comment]
Proposal prsented in Expert panel on 05/07/2021:

![grafik](https://user-images.githubusercontent.com/73635642/129047825-44533513-dd5b-4147-9aa2-738f0892bf9e.png)

**Comment by anborr** [comment]
I propose to move #202 here.

**Comment by anborr** [comment]
![grafik](https://user-images.githubusercontent.com/73635642/134464862-7686dc63-323c-4781-9287-0ecf8ad2719a.png)

**Comment by kazunorit** [comment]
@SergejMuhic @larswik
This is a sample geophysical survey data set for the voxel model. Please find the file format and other descriptions in the accompanying file. The data file is in UCD (unstructured) format, but if you prefer a structured format please let me know - I can change it.
[CaliforniaVs_withReliability.zip](https://github.com/bSI-InfraRoom/IFC-Specification/files/7261442/CaliforniaVs_withReliability.zip)
[Description.pptx](https://github.com/bSI-InfraRoom/IFC-Specification/files/7261443/Description.pptx)

**Comment by SergejMuhic** [comment]
I would propose addressing only IfcVoxelGrid with this issue as the data part seems to be a more general issue and we have it in other types of model related data.

**Comment by pjanck** [comment]
Resolved through #329
