### ISSUE TITLE
[IFC Tunnel] Guided sweep representation

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#118]
The requirement for sectioned sweeps (varying profiles) with the ability to parametrically describe the paths between profiles in a non-linear manner has been expressed. Once the proposal is presented at the expert panel, it will be posted here.

[DOCUMENTATION]
[2021-08-11_GuidedSweeps.pdf](https://github.com/bSI-InfraRoom/IFC-Specification/files/6968930/2021-08-11_GuidedSweeps.pdf)

Modified Diagram:
![guided_sweep_instance](https://user-images.githubusercontent.com/16683597/135834577-df4ca0bd-b1d5-4897-bc50-ecda31aebfe2.PNG)

Two proposals in EXPRESS:
[guided_sweep_1.txt](https://github.com/bSI-InfraRoom/IFC-Specification/files/7276785/guided_sweep_1.txt)
[guided_sweep_2.txt](https://github.com/bSI-InfraRoom/IFC-Specification/files/7276786/guided_sweep_2.txt)

**Comment by anborr** [comment]
When having a closer look on `IfcArbitraryClosedProfileDef` I noticed that it is possible to use `IfcPointByDistanceExpression` to define the `StartPlacement` of any IfcCurveSegment:
[2021-08-11_GuidedSweeps_IfcArbitraryClosedProfileDef.pdf](https://github.com/bSI-InfraRoom/IFC-Specification/files/6969053/2021-08-11_GuidedSweeps_IfcArbitraryClosedProfileDef.pdf)

Wouldn't that solve our problems?

**Comment by anborr** [comment]
![grafik](https://user-images.githubusercontent.com/73635642/129044923-d5ebccb2-f8eb-4cb2-8bc9-ce8b7ba1dbc5.png)

**Comment by pjanck** [comment]
I oppose introducing `IfcLinearlyReferencedProfileDef` (as already expressed in the expert panel). 

As I understand, all `IfcProfileDef` are defined in x-y plane and can be used for all sorts of extrusions / lofts, etc. I can't imagine, how an `IfcExtrudedAreaSolid` would look like using the newly proposed profile def, placed with an `IfcLocalPlacement` somewhere away from the alignment. IMHO, it messes with too many well established concepts.

Regarding using `IfcPointByDistanceExpression` as the `Location` of a `IfcCurveSegment` within an `IfcArbitraryClosedProfileDef` - I believe that this would be contradictory, since the profile demands 2D placement, while it is required to be in 3D (as presented in the sketch).

**Comment by SergejMuhic** [comment]
Albeit `IfcCurveSegment.Placement` is an `IfcPlacement`, meaning it can be a linear placement (`IfcAxis2PlacementLinear`) or the existing Cartesian based placements (`IfcAxis2Placement`). The curves are defined by `IfcPointByDistanceExpression` based the alignment already. However, `IfcAxis2Placement2D.Location` cannot take `IfcPoint`, it is restricted to `IfcCartesianPoint`.

![image](https://user-images.githubusercontent.com/16683597/129079768-7e75744e-9019-4b48-98c1-18498ea12399.png)

This was restricted for exactly this purpose as it requires some acrobatics to achieve this sort of a geometric specification.

To @pjanck's point on `IfcLinearReferencedProfileDef` we are looking into this. You are right in that an IfcProfileDef based definition is not a solution. We do have the initial proposal:
```
ENTITY IfcGuidedCurveSolid
 SUBTYPE OF (IfcGuidedSweep);
	Profiles : LIST[2:?] OF LIST[3:?] OF IfcPointByDistanceExpression;
 WHERE
	ProfileSameDistanceAlong : SIZEOF(QUERY(temp <* QUERY(temp1 <* temp | temp1.DistanceAlong <> temp[0])) = 0;
	// todo same number of profile points
	// todo points on same plane
	// same basis curve in Profiles
END_ENTITY;
```
with a two dimensional `LIST` of `IfcPointByDistanceExpression` that would be a possible parametric alternative. It does not resolve the problem with the profile curves however.

Another possibility would be a new profile type, not based on IfcProfileDef:
```
ENTITY IfcLinearlyReferencedProfileDef
	[OPTION1] ProfilePoints : LIST[3:?] OF IfcPointByDistanceExpression;
        [OPTION2] OuterCurve : IfcCompositeCurve;
  WHERE:
	[OPTION1] WR1 : SIZEOF(QUERY(temp <* ProfilePoints | temp.BasisCurve <> ProfilePoints[1].BasisCurve)) = 0; // all basis curve reference in points are the same
        [OPTION2] WR1 : 'IFC4X3_RC4.IFCCURVESEGMENT' IN TYPEOF(OuterCurve); // mandating IfcCurveSegment
END_ENTITY;
```

**Comment by anborr** [comment]
I propose to change the WHERE rule `LocationIsCP` in IfcAxis2Placement2D to include also `IfcPointByDistanceExpression`. This is a minimalistic intervention that would allow us to implement Guided Sweep Solids in a lean way, by just reusing the existing `IfcArbitraryClosedProfileDef` with all its capabilities, including the description of the profile curves... 
Alternatively, the `StartPlacement` of `IfcCurveSegment` could be extended to hold also linear placements...

**Comment by SergejMuhic** [comment]
> I propose to change the `WHERE` rule `LocationIsCP` in `IfcAxis2Placement2D` to include also `IfcPointByDistanceExpression`.

Well this is exactly the point that @pjanck made. `IfcAxis2Placement2D` is a 2D placement (has a 2D `Location`). It's `RefDirection` can only have two dimensions and it does not feature an Axis attribute. It also has the following WR:
```
  RefDirIs2D : (NOT (EXISTS (RefDirection))) OR (RefDirection.Dim = 2);
  LocationIs2D : SELF\IfcPlacement.Location.Dim = 2;
```

Similarly `IfcAxis2Placement3D` is not suitable to have `Location : IfcPointByDistanceExpression` because `RefDirection` and `Axis` do not have the same descriptions as `IfcAxis2PlacementLinear` and work differently as the context is bound to a curve.

Consequently, we have to realize that the template `Product Linear Placement` always requires an `IfcLinearPlacement` being placed relative to the `IfcLocalPlacement` of an `IfcLinearPositioningElement`.

**Comment by SergejMuhic** [comment]
Updated the issue with two proposals in `EXPRESS`.

**Comment by anborr** [comment]
We now provide a second, simplier option that allows using conventional profiles in 2D space. In addition, GuidingCurves are described independently as `IfcSegmentedReferenceCurve` using `IfcPointByDistanceExpression` to relate them to the underlying Alignment. 

The downside, however, is that the `IfcCartesianPoint` of the profile and the corresponding`IfcPointByDistanceExpression` of the GuidingCurve must be linked explicitely and might have slightly diverging locations. Consistency must be ensured/checked by the implementors, potentially by defining an upper threshold for the acceptable distance between them.

![grafik](https://user-images.githubusercontent.com/73635642/142437690-6073401d-f1c1-4690-bb48-9fe5c5e3cf35.png)

**Comment by SergejMuhic** [comment]
A simpler proposal and easier to implement would be to specify a sweep and a derived IfcGeometricCurveSet for guiding curves.

**Comment by SergejMuhic** [comment]
> A simpler proposal and easier to implement would be to specify a sweep and a derived IfcGeometricCurveSet for guiding curves.
> 
> See the example of `Axis 2D Geometry` and `Body Swept Solid Geometry` usages: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcwall.htm that are both on `IfcWall` occurrences in IFC RV1.2 datasets.

This is taken as the resolution and we proceed with closing the issue and associated PR.
