### ISSUE TITLE
Sub schema assignments

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#122]
The following tasks are to-do:
  |   | Current | To-do
-- | -- | -- | --
  |   | IfcPortsAndWaterways | IfcPortsAndWaterwaysDomain
  |   | IfcRail | IfcRailDomain
  |   | IfcRoad | IfcRoadDomain
  |   |   |  
IfcSharedInfrastructureElements |   |   |  
  |   | IfcBuiltSystem | IfcProductExtension
  |   | IfcImpactProtectionDevice |  
  |   | IfcImpactProtectionDeviceType |  
  |   | IfcSign |  
  |   | IfcSignType |  
  |   | IfcSignal |  
  |   | IfcSignalType |  
  |   |   |  
  |   |   |  
  |   | IfcAnnotationTypeEnum | IfcProductExtension
  |   | IfcBuiltSystemTypeEnum | IfcProductExtension
  |   | IfcFacilityPartCommonTypeEnum | IfcProductExtension
  |   | IfcFacilityPartTypeSelect | IfcProductExtension
  |   | IfcFacilityUsageEnum | IfcProductExtension
  |   | IfcInterferenceSelect | IfcProductExtension
  |   | IfcTransportElementNonFixedTypeEnum | IfcProductExtension
  |   | IfcTransportElementTypeSelect | IfcProductExtension
  |   | IfcSpatialReferenceSelect | IfcProductExtension
  |   |   |  
  |   |   |  
  |   | Pset_Uncertainty | IfcProductExtension
  |   |   |  
  |   |   |  
  |   |   |  
IfcPortsAndWaterways |   |   |  
  |   | Pset_EnvironmentalEmissions | IfcProductExtension
  |   | Pset_MaintenanceStrategy | IfcSharedFacilitiesElements
  |   | Pset_MaintenanceTriggerCondition | IfcSharedFacilitiesElements
  |   | Pset_MaintenanceTriggerDuration | IfcSharedFacilitiesElements
  |   | Pset_MaintenanceTriggerPerformance | IfcSharedFacilitiesElements
  |   | Pset_ProcessCapacity | IfcProductExtension
  |   | Pset_ProjectCommon | IfcKernal
  |   |   |  
  |   |   |  
  |   |   |  
IfcRail |   |   |  
  |   | IfcAlignmentCant | IfcProductExtension
  |   |   |  
  |   | IfcDistributionBoard | IfcSharedBldgServiceElements
  |   | IfcDistributionBoardType | IfcSharedBldgServiceElements
  |   | IfcElectricFlowTreatmentDevice |  
  |   | IfcMobileTelecommunicationsAppliance |  
  |   |   |  
IfcRoad |   |   |  
  |   | IfcOpenCrossProfileDef | IfcProfileResource
  |   | IfcRelAssociatesProfileDef | IfcProductExtension
  |   | IfcSectionedSurface | IfcGeometryResource

**Comment by AlexBrad1eyCT** [comment]
After #120 

  |   | Current | To-do
-- | -- | -- | --
  |   | IfcRail | IfcRailDomain
  |   | IfcRoad | IfcRoadDomain
  |   |   |  
IfcSharedInfrastructureElements |   |   |  
  |   | IfcBuiltSystem | IfcProductExtension
  |   | IfcImpactProtectionDevice |  
  |   | IfcImpactProtectionDeviceType |  
  |   | IfcSign |  
  |   | IfcSignType |  
  |   | IfcSignal |  
  |   | IfcSignalType |  
  |   | IfcAnnotationTypeEnum | IfcProductExtension
  |   | IfcBuiltSystemTypeEnum | IfcProductExtension
  |   | IfcFacilityPartCommonTypeEnum | IfcProductExtension
  |   | IfcFacilityPartTypeSelect | IfcProductExtension
  |   | IfcFacilityUsageEnum | IfcProductExtension
  |   | IfcInterferenceSelect | IfcProductExtension
  |   | IfcTransportElementNonFixedTypeEnum | IfcProductExtension
  |   | IfcTransportElementTypeSelect | IfcProductExtension
  |   | IfcSpatialReferenceSelect | IfcProductExtension
  |   |   |  
  |   | Pset_Uncertainty | IfcProductExtension
  |   |   |  
IfcRail |   |   |  
  |   | IfcAlignmentCant | IfcProductExtension
  |   |   |  
  |   | IfcDistributionBoard | IfcSharedBldgServiceElements
  |   | IfcDistributionBoardType | IfcSharedBldgServiceElements
  |   | IfcElectricFlowTreatmentDevice |  
  |   | IfcMobileTelecommunicationsAppliance |  
  |   |   |  
IfcRoad |   |   |  
  |   | IfcOpenCrossProfileDef | IfcProfileResource
  |   | IfcRelAssociatesProfileDef | IfcProductExtension
  |   | IfcSectionedSurface | IfcGeometryResource

**Comment by AlexBrad1eyCT** [comment]
on merge of #123 

  |   | Current | To-do
-- | -- | -- | --
  |   | IfcRail | IfcRailDomain
  |   |   |  
IfcRail |   |   |  
  |   | IfcAlignmentCant | IfcProductExtension
  |   |   |  
  |   | IfcDistributionBoard | IfcSharedBldgServiceElements
  |   | IfcDistributionBoardType | IfcSharedBldgServiceElements
  |   | IfcElectricFlowTreatmentDevice |  
  |   | IfcMobileTelecommunicationsAppliance |

**Comment by czapplitec** [comment]
On pull request #128 

<html>
<body>


  |   | Current | Done
-- | -- | -- | --
  |   | IfcRail | IfcRailDomain
  |   |   |  
IfcRail |   |   |  
  |   | IfcAlignmentCant | IfcProductExtension
  |   |   |  
  |   | IfcDistributionBoard | IfcElectricalDomain
  |   | IfcDistributionBoardType | IfcElectricalDomain
  |   | IfcElectricFlowTreatmentDevice |  IfcElectricalDomain
  |   | IfcMobileTelecommunicationsAppliance |  IfcElectricalDomain
  |   | IfcElectricFlowTreatmentDeviceType |  IfcElectricalDomain
  |   | IfcMobileTelecommunicationsApplianceType |  IfcElectricalDomain


</body>
</html>

As a subtype of IfcFlowController, IfcDistributionBoard is moved to IfcElectricalDomain, as this one was proposed to replace IfcElectricalDistributionBoard.
