### ISSUE TITLE
Corrections to the illustration for IfcAlignmentVerticalSegment

### ISSUE THREAD

**Issue by clfey** [bSI-InfraRoom/IFC-Specification#131]
- [ ] The ‘x’ axis should be named «DistAlong”, which is the free parameter for this axis. 
- [ ] The ‘x’ axis shall not be shown with “STATION” values involving a ‘+’ sign since this is NOT a Relative Linear Reference Measurement but an Absolute LRM. Use ordinary real numbers.
- [ ] The "AE6" and "AA8" texts have not been explained. Remove?
![image](https://user-images.githubusercontent.com/8375198/124378531-20f2bb00-dcb2-11eb-948b-1d343af14b81.png)

**Comment by SergejMuhic** [comment]
To my knowledge, this image was adopted not authored. I would be happy to replace it if you could produce an equivalent, more precise alternative. I agree with all points listed.

**Comment by SergejMuhic** [comment]
Thanks @clfey for an updated image. Have tested with documentation to make it fit (md does not allow scaling and I did not want to change the image link).

Let me know what you think:
![image](https://user-images.githubusercontent.com/16683597/124394480-ee6faf00-dcff-11eb-833c-75db74cc268e.png)

To me, it looks good. Huge improvement. Thanks again @clfey!

**Comment by clfey** [comment]
Looks right to me as well, thanks Sergej :-)
