### ISSUE TITLE
IfcPavement has no Where rules

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#14]
Just noticed when working on the where rules for select enums that IfcPavement has no where rules. Not sure whether it should have a PDT but the 'Correct type assigned' is definitely missing. I did add the correct type assigned before, maybe it got lost in the conversion process?

What do we do about it especially PDT?

**Comment by larswik** [comment]
Hmmm, for road the only "types" of pavement from the requirements were "Flexible" vs "Rigid". Currently this is handled with the boolean attribute "Flexible". I don't remember why that decision was made. Maybe better to use a PDT with {FLEXIBLE, RIGID, USERDEFINED and NOTDEFINED} instead?
Regarding the IfcPavementType, the discussion was that the composition of a pavement could be "typed". Does that make sense?  => "Correct type assigned" is necessary.

**Comment by SergejMuhic** [comment]
Okay, I will add the 'Correct type assigned' again. Really curious where it got lost.

From the point of view of how entities are modeled, I guess it would make sense to have a PDT instead of the bool. As you say, it then enables to guide applicability based on that too, If that is agreed, I would support such a modification.

**Comment by larswik** [comment]
**From PIARC:**
flexible pavement
Theme : Roads Construction Flexible and Semi-Rigid Pavements
Definition : Pavement with a bituminous surfacing and with a base layer with or without a hydrocarbon binder.

rigid pavement
Theme : Roads Construction Rigid Pavements
Definition : Pavement substantially constructed of cement concrete.
Synonyms : concrete pavement

**Comment by AlexBrad1eyCT** [comment]
I think the original thinking was that we could not come up with a satisfactory list for the PDTs, and when we had no PDTs we opted to not include the property.  the Flexible property is from original developments and if everyone thinks it is suitable to to convert it to a PDT then i agree.

**Comment by SergejMuhic** [comment]
Very good. In that case, I would remodel this part and add the rules.

**Comment by AlexBrad1eyCT** [comment]
addressed and merged into main there closing issue
