### ISSUE TITLE
Error or inconsistancy on IfcSectionedSurfaceHorizontal

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#19]
### Issue

There is an error being thrown by the where rule on `IfcSectionedSurfaceHorizontal` trying to access `temp.OffsetLongitudinal`. Currently, the entity is defined as follows:

```
ENTITY IfcSectionedSolidHorizontal
 SUBTYPE OF (IfcSectionedSolid);
	CrossSectionPositions : LIST [2:?] OF IfcCurveMeasureSelect;
	FixedAxisVertical : IfcBoolean;
 WHERE
	CorrespondingSectionPositions : SIZEOF(CrossSections) = SIZEOF(CrossSectionPositions);
	NoLongitudinalOffsets : SIZEOF(QUERY(temp <* CrossSectionPositions | EXISTS(temp.OffsetLongitudinal))) = 0;
END_ENTITY;
```

The rule is accessing `OffsetLongitudinal` but it does not exist on either options of `IfcCurveMeasureSelect` of `IfcNonNegativeLengthMeasure` or `IfcParameterValue` which are both type definitions.

### Solutions

1.  if `IfcCurveMeasureSelect` is the correct attribute for `IfcSectionedSolidHorizontal.CrossSectionPositions` update/remove the where rule to reflect the resent attribute typing change.
2. correct the attribute typing back to `IfcPointByDistanceExpression` which has the relevant attribute for the where rule 

### Footnotes

this is related to error within this [pull request #52](https://github.com/bSI-InfraRoom/IFC-infra-unit-test/pull/52) and this [issue #100](https://github.com/bSI-InfraRoom/IFC-infra-unit-test/issues/100)

*EDIT: Markdown syntax.*

**Comment by pjanck** [comment]
I would propose a third solution:

3. Remove the where rule `NoLongitudinalOffsets` altogether, since longitudinal offsets are no longer possible.

**Comment by AlexBrad1eyCT** [comment]
solution 1 says: 

> update/remove the where rule

if longitudinal offsets are no longer possible then solution 1 as removal is the implemented method 

1. who wants to do it!?? 
2. and then translate the change to the checker!?

**Comment by pjanck** [comment]
Right, missed that part - my bad :)

I believe Sergej updates the schema / documentation and forwards it to Andreas. That would be the course of action.  So @SergejMuhic - close this issue when you're done.

**Comment by SergejMuhic** [comment]
Have addressed this issue by changing the positions to IfcAxis2PlacementLinear as the cross sections require a context to be set and IfcPointByDistanceExpression does not provide it. Hence the rule should probably stay as I have no idea how to handle sweeps with discontinuous directrices.
