### ISSUE TITLE
[IFC Tunnel] IfcVoxel** feedback

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#202]
**Context**

#117 

**Feedback**

1. The naming of some entities in the PDF is inconsistent. Compare 

> ABSTRACT SUPERTYPE OF (IfcVoxelRealValues, IfcVoxelIntegerValues, IfcVoxelLogicalValues, IfcVoxelLabelValues…)

with

> ENTITY IfcIntegerVoxelValues

Between the two, I'd prefer the former: `IfcVoxel***Values`.

2. `IfcVoxelData` vs `IfcVoxelIntegerValues` 

I'd expect either `IfcVoxelIntegerData` or `IfcVoxelValues` - but not a mix of the two.

Again, between the two, I'd prefer the former: `IfcVoxelIntegerData`.

3. Documentation

I know that this has not been worked upon, so only a remark: I wish for a note that the `IfcVoxelGrid.Voxels` is `GridSizeX * GridSizeY * GridSizeZ` long and a note on their serialization order.

4. Praise

I like the individual simple types voxel data classes and support the decision for multiple classes in order to reduce file size.

**Comment by anborr** [comment]
(1) Yes, that's a mistake. We (the Tunnel project) tend to prefer Ifc***VoxelValues over IfcVoxel***Values, but we are flexible if others have strong opinions.
(2) I agree, the naming should be harmonized across superclass and subclasses. Hence we to have to decide between *Data and *Values.
(3) Serialization oder has been defined (inner loop iterates x, middle loop iterates y, outer loop iterates z) and will be documented.
(4) Thanks.
