### ISSUE TITLE
[IFC Tunnel] [Systems] Safety Other Elements

### ISSUE THREAD

**Issue by andrevonthron-RUB** [bSI-InfraRoom/IFC-Specification#205]
How does the other elements are working in the safety domain? Are they are elements or are they are part of a system?

* Fan -> Already in the ventilation domain. Will it also be put into a safety system? Do we need addtional fan types?

* Doors are IfcDoor and can be put into a specific system
  * Are they any new predefined types?
  * new properties necessary?

* Pictogram and Signage are considered as IfcSign (new in Ifc4x3) and could be of type IfcSignTypeEnum.PICTORAL
   --> can be used 

* What is meant by dramatization element? Some kind of a Sign?
  -> Already covered by chevrons and flash lights. it is some kind of group for that.

* Waiting Area -> IfcSpatialZone with IfcSpatialZoneTypeEnum.FIRESAFETY
   * TBD: New predifiended type? 

* Sound systems, such as sirens or sound beacons can be represented by an IfcSignal with IfcSignalTypeEnum.[VISUAL, AUDIO, MIXED]
 --> not specific enough, you must know if it is a siren or sth. else

* Handrails are realized by IfcRailing with IfcRailingTypeEnum.HANDRAIL
   * could include lighting for signaling, but in general belongs to the IfcRailing Element 

* Emergency Buttons/Panic Buttons could be realized by and IfcAlarm with IfcAlarmTypeEnum.BREAKGLASSBUTTON or something similar. The types of these Enum seem mixed with the type for signaling, such as SIREN or WHISTLE types, which could used in the IfcSignal (see sound systems above)
 --> New predefined type for EMERGENCYBUTTON necessary

* Other elements
   * Airlock -> Description required. Assuming to be an element to stop the airflow in case of fire.
       * is realized by a door or ventilation element, but should somehow be property of that elements
   * Flash fire -> Is it some kind of device, e.g. a flash light to signal an emergency case?
       * it is a visual signal or lamp to indicate an emergency case, i.e. a flash light  
   * Tracking -> ?
       * it is some kind of sensor, which can track die occurance and numbers of i.e. peoples or cars and their position inside the tunnel 
   * Guide chevron -> Its a Sign

**Comment by larswik** [comment]
Still open:
- Dramatization (proposal : Some kind of system but with a more generic name/concept)
- Tracking (proposal : Some kind of system but with a more specific name/concept)
- IfcSpatialZoneTypeEnum : Do we need a new PDT for WAITINGAREA or is FIRESAFETY enough?
- Airlock needs a mapping
- Operating manuel for fire fighters needs mapping
- Siren and Sound beacon needs a mapping
- Flash fire needs a mapping (signal or lamp indicating emergency)
- IfcAlarm/EMERGENCYBUTTON needed?
- Locks and “anti-panic system-bar” for doors

**Comment by anborr** [comment]
Dramatization: IfcDistributionSystem.WARNING_SYSTEM or IfcDistributionSystem.SAFETY_SYSTEM

**Comment by anborr** [comment]
Tracking: IfcDistributionSystem.MONITORINGSYSTEM

**Comment by anborr** [comment]
Waiting area, Airlock: IfcSpatialZone.FIRESAFETY
