### ISSUE TITLE
documentation improvements at IfcAlignment

### ISSUE THREAD

**Issue by TLiebich** [bSI-InfraRoom/IFC-Specification#211]
current documentation of IfcAlignment stil speaks about IfcAlignment.Axis - but this attribute had been deleted,

> Supported representations of IfcAlignment.Axis are:
> * IfcGradientCurve as a 3D horizontal and vertical alignment (represented by their alignment segments)
> * IfcCompositeCurve as a 2D horizontal alignment (represented by its horizontal alignment segments) without a vertical alignment
> * IfcOffsetCurveByDistances as a 2D or 3D curve defined relative to an IfcAlignmentCurve or another IfcOffsetCurveByDistances
> * IfcSegmentedReferenceCurve as a 3D curve defined relative to an IfcGradientCurve to incorporate the application of cant * IfcPolyline as a 3D alignment by a 3D polyline representation (such as coming from a survey)
> * IfcPolyline as a 2D horizontal alignment by a 2D polyline representation (such as in very early planning phases or as a map representation)

should refer to applicable shape representations for IfcAlignment and be compared with the concept template "Alignment Geometry Gradient" (e.g. enhance this concept template or add additional ones.

**Comment by TLiebich** [comment]
similar also above in the sentence:

> ...  where the child IfcAlignment may have Axis set to IfcOffsetCurveByDistances that starts and ends at a span within the extent of the original IfcAlignment defined at the Axis of the parent IfcAlignment.

**Comment by TLiebich** [comment]
the sentence:
> Alignments may be aggregated into referents (IfcReferent) or derivative alignments. 

should be extended to also refer of using nesting to decompose an IfcAlignment into its parts (horizontal, vertical, cant) and its segments (essentially linking to concept template "Alignment Decomposition")

**Comment by SergejMuhic** [comment]
Are you sure you have the right version? This was corrected in #146 

The documentation should look like this:
![image](https://user-images.githubusercontent.com/16683597/129777244-08315025-8aec-48d0-bb0d-117824ba25b4.png)

**Comment by SergejMuhic** [comment]
FYI, there were some issues with images not being copied over in constants. Images in constants also did not have updated numbering.

I have updated the documentation generation and created a PR (see #206) for `IfcAlignmentSegmentCantTypeEnum` which I will review with @apinzenoehler tomorrow. It might be that there are more constants that need updated md documentation.

**Comment by TLiebich** [comment]
thanks - I re-synced my github desktop, and I now see the most recent docu. So we can close this issue.
