### ISSUE TITLE
New IfcShapeRepresentation identifier: StringLines

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#22]
Proposal: add `StringLine` as a possible identifier for `IfcShapeRepresentation`. To be used for road edges / surveys / platform edge etc.

**Comment by AlexBrad1eyCT** [comment]
Is this necessary?? isnt the shape representation just an annotation identifier with a type curve. if you need additional semantics it could be encapsualated in an IfcAnnotation with the relevent PDT? or am i being niave and silly?
Lee has a few good unit tests on this with survey points and survey lines.

**Comment by pjanck** [comment]
Another proposal: change the documentation of the `Annotation` identifier to allow for 3D lines as well.
