### ISSUE TITLE
Alignment Geometry Cant Template

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#221]
## Description & Tasks
Geometry template for the definition Cant within Alignment As Sibling to Alignment Geometry Gradient. this is the geometry component of the related semantic template Issue #228 Alignment Cant and #256

- [x] Author Alignment Geometry Cant Template
- [x] Documentation of Alignment Geometry Cant Template

### Discussion Points
TBD

### Links
[Miro Element](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362581109449&cot=14)
[Miro Task Card](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362911087566&cot=14)

### Decisions 
1. Relating to #229 and #233 cant shall be used in certain geometry intensive cases such as sleeper, catenary post placement and geometric representations, structural gauge etc. The relative positioning in the semantic layer shall be covered with #233.

**Comment by SergejMuhic** [comment]
In general, `IfcAlignmentCant.Representation` would be of type `IfcSegmentedReferenceCurve` and `IfcAlignment.Representation` would keep the `IfcGradientCurve` type.
