### ISSUE TITLE
Surface Sectioned Geometry Template

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#224]
## Description & Tasks
Geometry template for the definition of sectioned surfaces 

- [ ] Author Surface Sectioned Geometry  Template
- [ ] Documentation of Body Surface Sectioned Geometry  Template
- [ ]  Add RepresentationType, if Needed

### Discussion Points

1. Does this require an additional RepresentationType or is it going to sit under Surface3D?

### Links
[Miro Element](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362582256473&cot=14)
[Miro Task Card](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362911087571&cot=14)

### Decisions 
TBD

**Comment by larswik** [comment]
I am not entirely sure about the status of #93 which relates to this.
I assume that a new CT like "Sectioned Surface geometry" is needed under "Surface geometry".
I also think that we would need a new representation identifier. Maybe "AdvancedSweptSurface" to align with the corresponding Body representations?
