### ISSUE TITLE
Body SectionedSolid Geometry Template

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#225]
## Description & Tasks
Geometry template for the definition of Body sectioned solids 

- [ ] Author Body SectionedSolid Geometry Template
- [ ] Documentation of Body SectionedSolid Geometry Geometry Template
- [ ]  Add RepresentationType, if Needed

### Discussion Points

1. Does this require an additional RepresentationType or is it going to sit under AdvancedSweptSolid?

### Links
[Miro Element](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362582255620&cot=14)
[Miro Task Card](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362911095418&cot=14)

### Decisions 
TBD

**Comment by larswik** [comment]
There is already a template "Body SectionedSolidHorizontal" sitting under "Body AdvancedSweptSolid Geomety". However, I am wondering what the closed issue #24 actually resulted in since nothing seem to have changed in the entity?

**Comment by AlexBrad1eyCT** [comment]
ahh, that got added after the last Doc gen run cause i used the IFC-Documentation repo to get the tree, in that case can you review it then add the documentation, i also suggest a name change to "Body SectionedSolidHorizontal Geometry.

with regards to #24 it is closed so i assume @SergejMuhic has employed the fix.

**Comment by SergejMuhic** [comment]
> 
> 
> There is already a template "Body SectionedSolidHorizontal" sitting under "Body AdvancedSweptSolid Geomety". However, I am wondering what the closed issue #24 actually resulted in since nothing seem to have changed in the entity?

Was not addressed yet as the PR is still open: #93
