### ISSUE TITLE
Linear Element Position Attributes Template

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#227]
## Description & Tasks
Template for Linear element position attributes

- [x] Author Linear Element Position Attributes Template
- [x] Documentation of Linear Element Position Attributes Template

### Discussion Points

1. Where does this template need to be placed in the hierarchy?
2. what is the content of the attributes where are they stored?

### Links
[Miro Element](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362583395129&cot=14)
[Miro Task Card](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362911095592&cot=14)

### Decisions 
TBD

**Comment by larswik** [comment]
I am not sure what is meant here? Some clarification please.

**Comment by larswik** [comment]
Is this a duplicate of stationing?

**Comment by AlexBrad1eyCT** [comment]
2. Content of Attributes

Associatation of Design parameters from a Rail point of view to areas of the Alignment.

This Template is about Assigning Attributes to an IfcLinearElement.

**Comment by AlexBrad1eyCT** [comment]
Addressed by PR #266
