### ISSUE TITLE
Alignment Cant

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#228]
## Description & Tasks
Template for the sematic definition of Alignment Cant relates to #221 Alignment Cant Geometry and Alignment Scissor Cant #256 

- [ ] Author Linear Alignment Cant  Template
- [ ] Documentation of Alignment Cant Template

### Discussion Points

1. Where does this template need to be placed in the hierarchy?
2. what is the difference to the alignment cant geometry template?
3. Gather requirements for relationship to horizontal.

### Links
[Miro Element](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362975203642&cot=14)
[Miro Task Card](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362982559730&cot=14)

### Decisions 
TBD

**Comment by AlexBrad1eyCT** [comment]
Are we still expecting an Alignment Layout Cant under Alignment Composition (which is being changed to Alignment Layout)??

**Comment by czapplitec** [comment]
Alignment Decomposition already includes cant, so no need if Alignment Decomposition stays as it is. But there are two issues:
- Alignment Decomposition (or Alignment Layout) should be under Nesting
- Do we need a more generic CT that alignment only has horizontal and vertical (this can be named Alignment Layout)?Then the current Alignment Decomposition can be its SubTemplate, named Alignment Layout with Cant

**Comment by AlexBrad1eyCT** [comment]
closing this as this will be included in the last alignment update
