### ISSUE TITLE
Alignment Geometry Gradient Template Documentation

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#231]
## Description & Tasks

- [ ] Add Documentation for alignment geometry gradient Template

### Discussion Points

None ATM

### Links
[Miro Element](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362580107106&cot=14)
[Miro Task Card](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362911087565&cot=14)

### Decisions 
TBC

**Comment by SergejMuhic** [comment]
Adding an issue discussed in the implementers Friday meeting. We need to document the usage of `IfcCompositeCurve` for horizontal where the end segment is specified with zero length and a final points as IfcPlacement.

Still to be resolved whether this requirement is supposed to be on the semantic layout part.

**Comment by AlexBrad1eyCT** [comment]
Initially Submitted but requires review and improvement
