### ISSUE TITLE
Review Product Linear Placement Template

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#233]
## Description & Tasks
Review of Product Linear Placement is still correct and relevent in light of chagnes to alignment durinf deployment

- [x] Review Product Linear Placement Template
- [x] Update Documentation, if Needed
- [x] Updated Template, if Needed

### Discussion Points

1. Still correct in relation to Alignment Changes as created at IFC4.2?

### Links
[Miro Element](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362574420150&cot=14)
[Miro Task Card](https://miro.com/app/board/o9J_l5rJCLk=/?moveToWidget=3074457362911087570&cot=14)

### Decisions 
1. No Issues found,

**Comment by larswik** [comment]
I can't seem to find an issue around this but I think that I recall that each IfcProduct being linearly placed needs to have an IfcRelPositions relationship with the IfcLinearPositioningElement (IfcAlignment) that it uses for positioning (see e.g. [UT_LP_3](https://github.com/IFCRail/IFC-Rail-Unit-Test/tree/master/2_Linear%20Placement%20(LP)/UT_LP_3)). If this is true (@SergejMuhic - can you verify?), the CT needs to include this. I also propose to include a CT for "span placement" which uses exactly two IfcReferent (linearly placed)/IfcRelPositions for specifying that start and end of a "span".

**Comment by AlexBrad1eyCT** [comment]
Thanks @larswik, the primary purpose was to check if it is still correct, 
so i see 2 things:
1. Is circular relationship for IfcRelPositions correct and always held as lars points out @SergejMuhic 
2. Can we encode this in the IfcDoc interface or will it need a manual addition to the mvdXML? @jmirtsch, @SergejMuhic?

With regards to A span placement, I am happy to add it to the work list, I assume it would be the same as above with an additional constraint of exactly 2 on `PositionedRelativeTo` ?

**Comment by SergejMuhic** [comment]
We have to distinguish between `Linear Placement` and `Relative Positioning`. A combination of those would be defined as a usage on `IfcProduct`. Concept templates are supposed to be functional parts so, the smaller they are, the easier it is to build around them.

**Comment by larswik** [comment]
If Product Relative Positioning is required in this case, then I feel that it should be added explicitly as general usage. Otherwise maybe not.

**Comment by larswik** [comment]
One more thing: I wonder where it is stated that the IfcAxis2PlacementLinear.Location shall be of type IfcPointByDistanceExpression?

**Comment by jmirtsch** [comment]
> One more thing: I wonder where it is stated that the IfcAxis2PlacementLinear.Location shall be of type IfcPointByDistanceExpression?

There is a where rule, although it could do with a description, https://github.com/bSI-InfraRoom/IFC-Specification/blob/9f8baa64bafb0c7d12b073e9bed0a494ead29913/IFC4x3/Sections/Resource%20definition%20data%20schemas/Schemas/IfcGeometryResource/Entities/IfcAxis2PlacementLinear/DocEntity.xml#L16

**Comment by larswik** [comment]
Aah ok. I was wondering if it was the "WR1" with no description. Logging an issue...
