### ISSUE TITLE
[IFC Tunnel] [Excavation] Excavation/Fill vs IfcEarthworksCut/IfcEarthworksFill

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#235]
The definition of IfcEarthworksCut is:
_The resulting void from modification of existing terrain or road structure by excavation or by other means of removing material. 

NOTE Definition from ISO 6707-1: void that results from bulk excavation of material. 
NOTE The material excavated and either used as fill or discarded as waste is not modelled as Cut, but may be handled as a different concept (Resource) in the future._

It seems as if the definition would fit also for tunnel excavation even though I understood from discussions that the naming (the term) is not optimal. What to do? Alternatives:
- Leave Entity names and tweak definitions if needed
- Modify (generalize) Entity names + definitions
    - I guess a bit of a pain since that would mean changing the IFC 4.3 schema which is on its way to ISO in a while
-	Add separate entities for Tunnel
    - Grows the IFC schema and clear statements to distinguish excavation from earthworks cut will be needed.

**Comment by AlexBrad1eyCT** [comment]
Ok, im still not sure I see a definitive technical different betwwen open/surface excavations and underground excavations in terms of the representation within the standard or a model. I expect differences in property sets but that would only account for additional PDTs over an entirely new entity??... i agree the naming and docs could use some work, this issue there is changing the name at this stage is a procedural annoyance.

**Comment by larswik** [comment]
From discussion in the IFC Tunnel tech team.
![image](https://user-images.githubusercontent.com/25506404/133818597-ec2bc9c7-f5c5-4b14-b4a2-70a4189a7f95.png)

**Comment by larswik** [comment]
Updated to latest:
![image](https://user-images.githubusercontent.com/25506404/157010311-5551d051-0408-4d4e-9466-620f2bfb7140.png)
