### ISSUE TITLE
Proposal regarding IfcSectionedSolidHorizontal

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#24]
Due to the necessary change for IfcSectioneSolidHorizontal.CrossSectionPositions type the FixedAxisVertical might have lost its necessity as each of the profiles are located along the Directrix and get a local coordinate system from its placement. The removal of this attribute would mandate the coordinate system for every position.

A possibility would be to replace FixedAxisVertical with a FixedDirection : IfcDirection which would fix the direction of Z for the entire sweep.

The other option is simply removing the attribute and mandate the local coordinate system of IfcAxis2PlacementLinear.

Thrid option, revert to IfcCurveMeasureSelect and use FixedDirection for the entire sweep.

Fourth option, leave FixedAxisVertical. For 'FALSE' IfcAxis2PlacementLinear defined coordinate system is mandated for profiles.

**Comment by pjanck** [comment]
My vote goes for `FixedReference`.

**Comment by SergejMuhic** [comment]
The vote goes to removal for simpler implementation.
