### ISSUE TITLE
Design speed on alignment

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#251]
## Description & Tasks
Nesting of `IfcReferent` with design speed information

- [ ] Review Stationing usage and the generic Referent nesting

### Discussion Points

1. Is a new template required or can `Nesting` and `Property Sets for Objects` be used specified in a usage on the alignment using IfcReferent with a design speed change assigned?

### Links
TBD @AlexBrad1eyCT 

### Decisions 
TBD

**Comment by SergejMuhic** [comment]
1. @apinzenoehler looks into requirements from Rail side.
2. @larswik , @SergejMuhic get the example from @jmirtsch for analysis.

**Comment by AlexBrad1eyCT** [comment]
@czapplitec  can you confirm that this is addressed by #266, and whether any review needs to be done for possible GU entries?

**Comment by czapplitec** [comment]
We don't really want to define design speed, but just want to define a "container" that can attach properties like desgin speed. so in my view, it is addressed by #266.

**Comment by AlexBrad1eyCT** [comment]
See Comments Closed per PR #266
