### ISSUE TITLE
Child templates of Body geometry

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#252]
Child templates do not have the RuleID `Identifier` specified as in the top node `Body Geometry`
```
<Constraint Expression="Identifier[Value] = 'Body'" />
```
According to my knowledge, the inheritance is not a feature between concept templates.

CC @MatthiasWeise asking for some input to create a PR.

**Comment by AlexBrad1eyCT** [comment]
Ok, done some investigation and have the following findings:

1. IfcDoc UI/Logic: when you create sub templates in IfcDoc it automatically copies the parent Query structure to allow you to add additions, but the UI doesnot copy the Constraints on properties. this I believe is the cause of the missing contraints.
2. IfcDoc does serialise in docXML the entire structure of the sub CT to the folders which is as expected.

3.  inheritance via sub templates in mvdXML
> NOTE: Sub-templates have to repeat rule definitions from supertemplates in case they apply. Further restrictions can be added if necessary. If rules are not repeated, they do not apply for the subtemplates. 
lifted from mvdXML 1.1 documentation means that the entire rule should be serialized in case of subtemplates, IfcDoc DOES do this but the UI logic error of point 1 is the reason the constraint has been accidently missed.
@MatthiasWeise or @SergejMuhic is this still the same within mvdXML1.2?

will generate a correction PR

**Comment by MatthiasWeise** [comment]
Yes, this agreement is still part of mvdXML1.2. See section 3.2 in the specification (ConceptTemplate.SubTemplates).
