### ISSUE TITLE
IfcReferent/POSITION description needs to be updated

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#255]
Now:
Used to fully describe a linearly referenced location given by the linear element being measured (the IfcAlignment into which the IfcReferent is nested), the method of measurement (Pset_LinearReferencingMethod) and a measure value specified with a **_distance expression (Pset_DistanceExpression)_**. If a linear referencing method is specified for the position, it overrides any linear referencing method specified for the alignment.

Proposed change:
Used to fully describe a linearly referenced location given by the linear element being measured (the IfcAlignment into which the IfcReferent is nested), the method of measurement (Pset_LinearReferencingMethod) and a measure value specified with a **_station (Pset_Stationing)_**. If a linear referencing method is specified for the position, it overrides any linear referencing method specified for the alignment.

**Comment by SergejMuhic** [comment]
@larswik is this issue still relevant?

**Comment by larswik** [comment]
I think this one can be closed. The description has been generalized and does not speak about the non existing Pset_DistanceExpression anymore.
