### ISSUE TITLE
Alignment Scissor Cant

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#256]
## Description & Tasks
Template for the semantic definition of Alignment Scissor Cant relates to #221 Alignment Cant Geometry and Alignment Cant #228.

- [ ] Author Alignment Scissor Cant
- [ ] Documentation of Alignment Scissor Cant 

### Discussion Points

1. Where does this template need to be placed in the hierarchy?
2. what is the difference to the alignment cant geometry template?
3. Gather requirements ti identify differences to Alignment cant.

### Links
TBD

### Decisions 
TBD

**Comment by AlexBrad1eyCT** [comment]
@SergejMuhic @czapplitec 
Is this still an expected/needed concept template or has it been shifted to be a GU related to Alignment Cant #228 ?

**Comment by czapplitec** [comment]
I actually don't see the necessity of this CT. Requirements need to be clarified by @apinzenoehler. I didn't find cases that require 2 segments for cant in the scissor section.

**Comment by AlexBrad1eyCT** [comment]
Closing due to statement by @czapplitec if a requirement arises please reopen
