### ISSUE TITLE
`IfcGridPlacement` concept template missing PlacementRelTo

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#257]
With the introduction of `IfcObjectPlacement.PlacementRelTo`, the concept template for `IfcGridPlacement` should be updated correspondingly, i.e. the relative placement *must be* the placement of the `IfcGrid`.

Pinging (and assigning) @berlotti since this is building domain.

**Comment by berlotti** [comment]
Building domain currently does not touch concept templates until first phase of infra/rail is delivered. 

Tech backlog has 'updating ifcGrid to similair concept as Alignment' on the list, but that is not scheduled until beginning of October.

Suggest to update this issue as part of finishing phase 1.
