### ISSUE TITLE
[IFC Tunnel][Excavation]IfcEarthworksElement non-abstract?

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#260]
Is IfcEarthworksElement is not abstract. Is that by intention or a mistake?
Propose to make it abstract.

**Comment by AlexBrad1eyCT** [comment]
I am unsure of the original intent for whether it is abstract, but as of IFC4.3 we made a change to make supertypes instantiable to allow better semantics of use cases not covered currently within the spec. e.g. if you have a "built element" that is not covered by any of the subtypes you can just instantiate an _IfcBuiltElement_ and set the ObjectType, providing some semantics to the object and then get rid of the garbage bin that was IfcBuildingElementProxy.

I see no issue with leaving it instantiable just in case an "earthworks element" doesnt fall within Earthworks Fill or Rienforced soil semantics. If Ifc Tunnel feels that it has all possible types of "earthworks element" then place the abstract proposal there.

**Comment by larswik** [comment]
Propose to leave it instantiable.
