### ISSUE TITLE
IFC4.3 legacy issues

### ISSUE THREAD

**Issue by iegorychev** [bSI-InfraRoom/IFC-Specification#281]
Found couple issues in 4.3 schema, think they exist at least since IFC2X3, so probably this is a time to fix:

1. Seems should be: IfcSameCartesianPoint(ap1.Location, ap2.Location, Epsilon)

FUNCTION IfcSameAxis2Placement
            (ap1, ap2 : IfcAxis2Placement; Epsilon : REAL)
            : LOGICAL;
    RETURN (IfcSameDirection(ap1.P[1],ap2.P[1],Epsilon) AND
            IfcSameDirection(ap1.P[2],ap2.P[2],Epsilon) AND
            IfcSameCartesianPoint(ap1.Location,ap1.Location,Epsilon));
END_FUNCTION;

2. arg first letter is in lower case there in one line of IfcNormalise (I know EXPRESS is case insensitive, but...)

FUNCTION IfcNormalise
(Arg : IfcVectorOrDirection) 
    : IfcVectorOrDirection;
...
      IF 'IFC4X3_RC4.IFCVECTOR' IN TYPEOF(arg) THEN

**Comment by aothms** [comment]
I fixed these in https://github.com/buildingSMART/IFC4.3.x-development

**Comment by SergejMuhic** [comment]
@iegorychev syncing with the bSI repo. If you have an opportunity, please check the change. I would prefer to have a review, but these are small changes.

**Comment by iegorychev** [comment]
@aothms , @SergejMuhic Thanks, I'll check after weekends.

**Comment by SergejMuhic** [comment]
I found another capitalization in `IfcConstraintsParamBSpline` and will attach it to this issue and the linked PR if it is okay by you guys. The "Result" parameter in the return statement.

```
Result : BOOLEAN := TRUE;
...
  END_REPEAT;

  RETURN(result);
END_FUNCTION;
```
