### ISSUE TITLE
IfcShapeRepresentation Representation Identifier Body-Fallback

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Specification#30]
https://standards.buildingsmart.org/IFC/RELEASE/IFC4/FINAL/HTML/link/ifcshaperepresentation.htm

IfcShapeRepresentation has a table listing Representation identifiers.
If you refer to the change note below, it states 'Body-Fallback' was added as an identifier in IFC4.
However it's not listed in the table.  I'd like to see it listed explicitly in the table, but was it deliberately omitted and the note was not updated?

Cheers,

Jon

**Comment by SergejMuhic** [comment]
Good question. I really don't know about this. We would have to ask Matthias or Thomas about this.

**Comment by AlexBrad1eyCT** [comment]
its disappears as of IFC4x1 with the addition of a Reference identifier? is it an error no one caught or it has been intentionally removed

**Comment by TLiebich** [comment]
I also compared IFC4 and IFC4.1 and I can't recall why the Body-Fallback was left out (the new "Reference" identifyer is not related to it). Would propose to bring it back.
