### ISSUE TITLE
CT Element Attributes

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#300]
A template to specify basic element attributes. `IfcElement.Tag` for example for serial number.

**Comment by billeast** [comment]
FMH-EM requires several types of properties that may, or may not, be correctly implemented by underling software. Not all of the PSetCommon properties for objects found in FMH-EM are required. Other properties provided through design software that does not support or map equipment schedule data to formal IFC property sets must be accommodated. Properties created by software systems for purposes of viewing or plotting are explicitly outside the scope of FMH-EM and shall be filtered out.  Properties with default values (e.g. the name of the property is listed as the value of the property) shall also be filtered out.

**Comment by libalschwarzd** [comment]
Generally agree. One Proposal is for "InstalledModelNumber". 
Alternativ mapping "Pset_ManufacturerTypeInformation.ModelReference"  or "Pset_ManufacturerTypeInformation.ModelLabel"
Reason: Using exsiting attributes

**Comment by SergejMuhic** [comment]
The requirement is that it goes into psets. #324
