### ISSUE TITLE
CT Asset Assignment

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#301]
Potential new template requirement for IfcAsset.

**Comment by billeast** [comment]
A justification and description of this "helper" FMH-EM Concept Template is needed.

**Comment by libalschwarzd** [comment]
An IfcAsset is a uniquely identifiable grouping of elements acting as a single entity that has a financial value. Typically, terms are “trade” or “contractors’ scope of supply”   
This concept allows IfcElements to associate with one IfcAsset and one or more Systems. By rule a given IfcElement or IfcSystem will only be associated with a single IfcAsset. For example, the contractor for air conditioning systems will provide and install two heating systems (AC1 & AC2) which each has the element ventilator which are associated to IfcAsset as well.
As a rule IfcElementType that is related to an IfcElement that is associated to an IfcAsset can not be related to an IfcElement that is associated to another IfcAsset.

**Comment by billeast** [comment]
IfcAsset is now within FMH-EM scope. IfcSystem connects to one or more ifcProducts (of which FMH-EM only allows IfcElement -- by definition) through the IfcRelAssignsToGroup. 

From IfcSystem "The grouping relationship to one or several instances of IfcProduct (the system members) is handled by IfcRelAssignsToGroup."

"Asset" is -not- an IfcObject that has been used in the FMH-EM spreadsheet mapping requirement document. We must not broaden the scope of FMH-EM to support alternative implementations. Allowing alternative implementations leads to complications for testing software and testing project-based deliverables by those who will never understand these technical discussions.

**Comment by libalschwarzd** [comment]
Agree not to broaden the scope of FMH-EM.

**Comment by DrShawnOKeeffe** [comment]
We must eliminate IfcAsset from this MVD as it is out of scope. Technically IfcAsset deals with element groupings over fiscal periods and deals with finance and accounting information for assets over time etc. which is at a higher level than this MVD. FMH-EM MVD is down lower at a more granular level and we cannot introduce IfcAsset during the business process that satisfy this MVD spec.

**Comment by billeast** [comment]
Concur, this should be deleted.

**Comment by SergejMuhic** [comment]
Closing. See discussion.
