### ISSUE TITLE
CT Component to Distribution System

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#304]
Review for SystemNames

**Comment by billeast** [comment]
A justification and description of this "helper" FMH-EM Concept Template is needed.

**Comment by billeast** [comment]
FMH-EM requires the identification of building services to be identified by "System". This Concept allows IfcElements to associated with one (or more) Systems. Typically a given IfcElement will only be associated with a single system. For example, a lavatory, toilet, or urinal may be associated with a sanitary system. 

There are two instances where IfcElements might be associated with more than one System. The first occurs when large, building-wide IfcElements provide services to more than one System. For example a hot water boiler may be used both for a potable hot water distribution system and as part of the heating system. 

The second instance where an ifcElement could be assigned to more than one System occurs when there is an interface between systems. This situation would also require the specification of sub-systems. For example consider a sink or lavatory, the value(s) on the top of this IfcElement are certainly part of a potable water distribution system. The drain is also part of the waste water system. In most buildings, such distinctions may not be needed. However, should users wish to clearly distinguish between multiple waste systems, e.g. gray water vs. black water, then it may be important to provide more than one system association.

**Comment by billeast** [comment]
it is not clear why there is a need to connect to an IfcDistributionSystem when the more general IfcSystem is the connection that I have seen most implemented in STEP file presentations of past data. If IfcDistributionSystem is required, then I suggest that we specify exactly which IfcDistributionSystem categories would be allowed/supported and which are not supported. 

there also appears to be a problem with both IfcSystem and IfcDistributionSystem in that spatial objects are allowed to be referenced. This is -not- allowed in FMH-EM. IfcSystem are only for IfcElement. IfcZone are only for IfcSpace.

**Comment by DrShawnOKeeffe** [comment]
It should be IfcSytem. The IfcSystem.Name and other related data is suffice for knowing the type of system anyway.

DistributionSystem is only one type of system.

IfcSystem is suffice for the grouping of elements within/through spaces.

**Comment by billeast** [comment]
Concur ifcSystem should be used. This must also be restricted to collections of IfcElement objects.

**Comment by SergejMuhic** [comment]
The template structure shall  be used to modify `CT Assignment To Group`. #303

**Comment by libalschwarzd** [comment]
I recommend including the subclasses of IfcSystem (IfcBuiltSystem and IfcDistributionSystem) as allowed classes.
