### ISSUE TITLE
Branch concept_template review

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#31]
If you find a couple of minutes, I have revised the folder structure of concept templates. It can be found in the concept_template branch where you have to navigate to the 'Templates' folder.

**Comment by pjanck** [comment]
I quite like it - it's based on the SubTemplates tree within the ConceptTemplate tree, right?

I believe, if this one :https://github.com/bSI-InfraRoom/IFC-Specification/blob/concept_template/IFC4x3/Templates/Partial%20Templates/Profile%20Definition/Arbitrary%20Profile%20Definition/PolyCurve%20with%20Voids%20Profile%20Definition/DocTemplateDefinition.xml isn't too long anymore, it's a plus!
