### ISSUE TITLE
New Entity IfcLayout

### ISSUE THREAD

**Issue by arch1501** [bSI-InfraRoom/IFC-Specification#314]
A PlanLayout represents a 2D plan view - also called Paper Space - used for PDF outputs or printings. Each PlanLayout  contains  basic drawing  elements  like  drawing  frame,  text field,  title  block,  legend  and additionally one or more Viewports (see IfcViewport).

**Comment by TLiebich** [comment]
to me, both the view port and the layout are two significant extensions to IFC (there was a long time ago a similar proposal from Korea). In my view, it needs to be properly addressed by an IFC extension project - better submit it to the main IFC repository at bSI. Not sure that it will be taken on board by the ifcra projects and hence may not be best placed here.

**Comment by arch1501** [comment]
@TLiebich Are there any information available about the mentioned prposal from Korea?

**Comment by Moult** [comment]
Closing as not part of IFC infra project. Continue discussion in 4.3.x-dev.
