### ISSUE TITLE
[IFC Tunnel] [Geotechnics] - Book B proposal after discussion 2021-11-26

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#315]
![image](https://user-images.githubusercontent.com/25506404/143587888-af3884ce-5f6a-4ba7-856e-13eb84bddfdb.png)

**Comment by j-weil** [comment]
Regarding boreholes:
The 4x3 proposal schema sees borehole as a type of representation fo the interpreted model aling the axis of the holes.
This is (to our understanding in the Geo Subgroup) NOT in line with our requirement to support basic observations and original logs in boreholes. In terms of our current schemal proposals:
GeoScienceObservations (Factual data, Book A) are different from GeoScienceElement, Assembly,... (Interpreted Models, Book B)
Reason: The data are frequently generated by different actors, described in different reports and have different meaning in contracts. Classifications and descriptions are NOT necessaryly in line with Book B, and it has to be avoided that this is mixed up.

**Comment by larswik** [comment]
Personally, I would prefer having only one semantic entity in IFC representing the concept of a borehole and separate the various representations of it. Can the definition for IfcBorehole be looked at and perhaps tweaked? Is the term IfcGeoScienceElement not the right one? The way this would be handled according to the current proposal is that the actual observations are separate objects (under IfcProductData) that are linked to e.g. borehole (which is the "container").

**Comment by larswik** [comment]
Updated UML model:
![image](https://user-images.githubusercontent.com/25506404/157014110-d264bac3-542c-4a7b-b34f-f58362ddf759.png)

![image](https://user-images.githubusercontent.com/25506404/157014139-eeeb2983-c7d5-440c-8fee-3314df2fe5f9.png)
