### ISSUE TITLE
[IFC Tunnel] [Geotechnics] - Make it possible to link external datasets to IFC Entities (such as boreholes or sensors)

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#316]
Since there are existing formats (often csv or similar) to capture measurements, observations etc it is maybe not a good idea to always "emulate" these formats in IFc Entities, Psets or similar. Therefore the ability to link external data to IFC Entities could be a good way to keep all available data still connected. Parts of proposal below. More work is needed around MvdXML definitions to allow and better specify this is still needed.
![image](https://user-images.githubusercontent.com/25506404/143589466-fa938c39-8b55-4326-938a-114677d69f0d.png)

**Comment by j-weil** [comment]
Agreed that is is a good approach for factual data like borehole data and test results (Geotech Taxonomy "Book A")
To be used for data like detailed borehole logs with small increments, MWD-data, CPT, borehole geophysical logs etc.

Short coming: More complex handling of models with linked files compared to “simple IFC models”. Visualization in common Viewers and integration in common standard CDE-solutions etc. presumably not supported
Proposed/agreed solution: Support both options
1.	BoreholeDataRepresenationInterval and -Point as supported objects (=fully supported by common BIM-software). These objects can be used to exchange and visualize where observations have been made and how the material was addressed (including a fist step of interpretation of “raw data”
Not too small increments/No. of data points and extensive list of properties/P-Sets, to allow for an efficient integration in the existing schema and, in practice, efficient data exchange. 
compare to https://github.com/bSI-InfraRoom/IFC-Specification/issues/315

**Comment by larswik** [comment]
My interpretation:
- Keep proposal for external data (large datasets with e.g. detailed borehole logs)
- Add in the schema entities/predefined types for BoreholeDataRepresentationInterval/-Point + Psets. Maybe an appropriate place would be under IfcProductData which is proposed for issue #317.

**Comment by larswik** [comment]
During discussions with the domain team it became clear that one external dataset can be used to represent data for many IFC objects (e.g. boreholes). This means that there may be a need to have a mechanism to relate a specified subset of the referenced dataset from an IFC entity. One example:
- A csv file with many rows where there is a field that specifies a borehole id.
- For each borehole entity in IFC, the exact rows belonging to that borehole could be selected by selecting the rows where the identity field value equals the IfcBorehole.Name attribute.

One simple solution would be to be able to specify one or more fields as identity fields in the external dataset together with the metadata already available in IfcDocumentInformation.

**Comment by j-weil** [comment]
That sounds like a simple and adequate solution, fitting to common formats that are used to exchange borehole data.
Could it be applied in the same way to observations, like BoreholeDataRepresentations? E.g.:
- the IFC entity (e.g. BoreholeDataRepresentation) has the attributes "IfcBorehole.Name", "depth from" and "depth to", 
- the corresponding rows are contained and identified in the external dataset, and relevant information can be used like a "custom Pset"?

**Comment by j-weil** [comment]
The same principle could be used for other observations like samples and test results, using Sample name instead of Borehole name

**Comment by billeast** [comment]
Please consider that to be extensible to other domains a generic representation of mappings to/from other data presentations/flavors should be specified. If done correctly, the FMH-EM project would be able to directly adopt this approach as well as covering the use case above. 

There are many situations where tabular/relational data is captured/managed outside the tools that provide geometric presentations but there is a need to maintain the relationships among these data sets.

**Comment by larswik** [comment]
Thanks @billeast. Good to have that requirement logged here. Please log any related requirements here as well. I think that the aim for this functionality is to add it to the IfcExternalReferenceResource part of the IFC schema (same as e.g. IfcClassificationReference, IfcDocumentReference, IfcLibraryReference etc) which means that it must provide a generic mechanism. When finalized, the proposal therefore needs to be reviewed also by experts outside of the IFC Tunnel project. I also add the link to the standard [ISO 21597-1:2020](https://www.iso.org/standard/74389.html) which might provide relevant input.

**Comment by j-weil** [comment]
Thanks from my side, too. 
We just had a discussion in the geo-group and see another important application for this functionality, beside observations and test results:
For geotechnical design models, the mechanical behaviour of inhomogeneous ground is commonly described by many different constitutive material models. Covering all these models in the properties of geotechnical units is impossible, but linking an external file with the custom definition of a material model to a "proxy-Pset GeoMaterialModel" would be a great option.

**Comment by larswik** [comment]
From discussion with Nick N: Consider this also for Voxel data.

**Comment by j-weil** [comment]
Indeed, we think that this is the right approach for geophysical surveys or similar extensive data sets represented by Voxel models
