### ISSUE TITLE
[IFC Tunnel] [Geotechnics] - Enable a mechanism to connect observations of different kinds to physical objects or other "containers" such as zones

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#317]
For geotechnics/geology, factual data such as observations and tests need to be assigned to physical objects and zones such as boreholes and mapped zones. Similar mechanisms could be used in the future e.g. for recording e.g. inspection data on existing constructions (e.g. bridge inspections). Proposal below:
![image](https://user-images.githubusercontent.com/25506404/143589978-aa19b8d2-08e7-459c-9e4b-1e3f9276c8a4.png)

**Comment by larswik** [comment]
Question from meeting 2021-11-26. Should observations and tests be separated:
![image](https://user-images.githubusercontent.com/25506404/143590198-75fe3db1-fbb0-4498-b998-e33fe2921b5c.png)

**Comment by j-weil** [comment]
As agreed it would be helpful to get some bullet-points on key aspects when definition of subtypes is recommended in the schema, so that we can discuss this in the group and make a proposal.

**Comment by billeast** [comment]
Documents and properties should be available for attachment to any object, including those above IfcProduct. In buildings for example we need a way to capture information about the building, storey, space, zone, and system as well as with IfcElementType(s) and IfcElements. We even need to attach information to IfcPersonAndOrganization when, for example, a certificate or qualification credential is submitted for a company or an individual. 

This use-case goes well beyond Tunnels to all project/facility types! I suggest it be nominated as a schema change. to simply allow IfcRel objects to be linked to any other object based on the specifics of the MVD/IDS.

**Comment by billeast** [comment]
Regarding different types of 'observations' from the example above. I suggest there be a generic link to attaching data to any object within a spatial or product hierarchy The relation that attaches that data set should identify its classification. The classification should not be on the data itself.
