### ISSUE TITLE
[P&W] Property issues

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#327]
I would also use this issue to point out a couple more. Forgot a couple of times now to post these:
1. https://github.com/bSI-InfraRoom/IFC-Specification/tree/develop/IFC4x3/Properties/h/HydraulicConductivity_0n5hy7wA9CGeRruzAkgVAG
and
https://github.com/bSI-InfraRoom/IFC-Specification/tree/develop/IFC4x3/Properties/p/PwaveVelocity_25QNLFrcX23AOU3hgpu9do
also
https://github.com/bSI-InfraRoom/IFC-Specification/blob/develop/IFC4x3/Properties/s/SwaveVelocity_0Zt9yzVWjF3QUsVuryk8eT/DocProperty.xml
should be `IfcLinearVelocityMeasure`
2. https://github.com/bSI-InfraRoom/IFC-Specification/tree/develop/IFC4x3/Properties/l/LoadbearingCapacity_2r2w0IRgj2ZPPZHhlnoADU
maybe a typo in the name and the PrimaryDataType should be `IfcPressureMeasure`

_Originally posted by @SergejMuhic in https://github.com/bSI-InfraRoom/IFC-Specification/issues/326#issuecomment-991717860_

**Comment by aothms** [comment]
Yes, thanks, I was just about to post these. But I have a couple more.

issue | prop
---------------------------------------------------------------------------------------------------------------------------|----
TypePropertySingleValue Type `IfcBoreholeState` does not exist | Pset_BoreholeCommon.BoreholeState
`PEnum_ProcessItem` encoded as a TypePropertySingleValue so doesn't have EnumList | Pset_CargoCommon.ProcessItem, Pset_ProcessCapacity.ProcessItem | 
TypePropertySingleValue Type `IfcVelocityMeasure` does not exist | Pset_ElementKinematics.MaximumConstantSpeed,  _Pset_SolidStratumCapacity.HydraulicConductivity, Pset_SolidStratumCapacity.PwaveVelocity, Pset_SolidStratumCapacity.SwaveVelocity_
TypePropertySingleValue Type `"IfcDuration "` with trailing space (minor) | Pset_ProcessCapacity.ProcessPerformance
TypePropertySingleValue Type `PressureMeasure` missing Ifc prefix | _Pset_SolidStratumCapacity.LoadbearingCapacity_

**Comment by AlexBrad1eyCT** [comment]
OK guys, will sort in a pull request thank you for spotting these.

**Comment by AlexBrad1eyCT** [comment]
#337 fixes the following
Sergej's points:

1. Fixed
2. Fixed

Thomas:
issue | State |
------|-------|
| TypePropertySingleValue Type `IfcBoreholeState` does not exist | Fixed |
| `PEnum_ProcessItem` encoded as a TypePropertySingleValue so doesn't have EnumList | Fixed | 
| TypePropertySingleValue Type `IfcVelocityMeasure` does not exist | Fixed |
| TypePropertySingleValue Type `"IfcDuration "` with trailing space (minor) | Fixed |
| TypePropertySingleValue Type `PressureMeasure` missing Ifc prefix | Fixed |
