### ISSUE TITLE
Removal of attribute IfcReferent.RestartDistance

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#344]
As title says, we want to remove `IfcReferent.RestartDistance` in favour of the `Pset_Stationing` property set.

https://github.com/buildingSMART/IFC4.3.x-development/issues/169

**Comment by larswik** [comment]
I assume deprecation instead of removal. Introduced in IFC 4.1.

**Comment by clfey** [comment]
CLFEY : No opinion concerning removal or deprecation.
