### ISSUE TITLE
[IFC Tunnel][Spatial structure] Lateral facility parts or spaces for IFC Tunnel

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#360]
A decision is needed to what degree we need to specify the possible "lateral" spaces in a tunnel. A meeting between @larswik , @SergejMuhic  and Jan Erik Hoel resulted in the following figure:
![image](https://user-images.githubusercontent.com/25506404/157031704-d8fc907e-3939-464f-a784-05189b17ff25.png)

However, in the IFC Tunnel RAR, all of the following are listed:
![image](https://user-images.githubusercontent.com/25506404/157031873-f82e144e-158b-4ca9-bdf9-59b2b8565c15.png)

![image](https://user-images.githubusercontent.com/25506404/157031938-c9c1526a-e4ee-4229-b2c0-40eded0d82d0.png)

![image](https://user-images.githubusercontent.com/25506404/157031995-fa70a58c-ea14-4831-89a6-afb67cbb9b8c.png)

![image](https://user-images.githubusercontent.com/25506404/157032046-6c3ff65e-7210-4c7a-bd1a-1bbe9f9223a2.png)

**Comment by larswik** [comment]
Proposal from meeting with @anborr @SergejMuhic and Jan Erik Hoel:
- Define entire tunnels as IfcTunnel (list of PDTs remains to be defined)
- Define longitudinal breakdown as IfcFacilityPart/IfcTunnelPart (exact list of PDTs remains to be defined)
- Use a small set of PDTs for IfcSpatialZone for lateral spaces (PDTs remains to be defined)

**Comment by anborr** [comment]
1. Define entire tunnels as IfcTunnel (list of PDTs remains to be defined).

2. Longitudinal breakdown:
Do we still have IfcFacilityPartTypeSelect? 
Proposed PDTs:
- PORTAL
- SHAFT
- CROSS_TUNNEL
- TUNNEL_SECTION

3. lateral spaces: SpatialZone 
Yes, small set of PDTs. I am in favor of Figure 7-9 above.

**Comment by larswik** [comment]
Decision 2022-03-24:
- Facility PDTs
  - ACCESSTUNNEL
  - SHAFT
  - UTILITIES (includes e.g. water, gas, high voltage)
  - ROAD
  - RAILWAY
  - METO
  - PEDESTRIAN
  - BICYCLE
  - MAINTENANCE
  - UNDERGROUND_FACILITIES
- Facility parts (longitudinal subdivision)
  - TUNNELSECTION
  - RINGSECTION
  - CROSSWAY
  - PORTAL
- Spatial zones (lateral subdivision) - should "SPACE" be included in the name?
  - ANNULARGAP
  - LINING
  - INTERIOR
  - SERVICE
  - CLEARANCE
  - INVERT
  - INSTALLATION
