### ISSUE TITLE
[IFC Tunnel][Excavation] - IFC mappings needed for tunnel some support elements

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#364]
- Retention wall (assumed IfcWall/RETAININGWALL)
- Lagging
- Yielding support
- Liner plates

**Input (explanation, illustrations) needed from domain team.**

**Comment by JanErikHoel** [comment]
See attached document
[réponse à JanErik 15022022.docx](https://github.com/bSI-InfraRoom/IFC-Specification/files/8301936/reponse.a.JanErik.15022022.docx)

**Comment by larswik** [comment]
Retention wall:
We have on the one hand retention basin that are used for sewage, and retaining walls for cut and covers.

Lagging:
??

Liner plates:
![image](https://user-images.githubusercontent.com/25506404/159011188-efc486bd-fec4-45e9-b33b-f7e459d5653a.png)


IfcPlate predefined types:
CURTAIN_PANEL | A planar element within a curtain wall, often consisting of a frame with fixed glazing.
SHEET | A planar, flat and thin element, comes usually as metal sheet, and is often used as an additonal part within an assembly.
FLANGE_PLATE | A flange plate in linear members having box or I-profile (e.g. top or bottom flange plate in box-girder).
WEB_PLATE | A plate connecting flange plates in linear members having box or I-profile.
STIFFENER_PLATE | A transversal plate added to a flange or a web plate for local stiffening.
GUSSET_PLATE | a plate or bracket for strengthening an angle in framework (as in a building or bridge).
COVER_PLATE | A plate (underneath or above) a flange to provide additional load capacity.
SPLICE_PLATE | A plate connecting two members joined at ends.
BASE_PLATE | A plate used to spread load over a surface, such as underneath a bearing or column.

Yielding support:
![image](https://user-images.githubusercontent.com/25506404/159010985-2a757483-47eb-4fb9-a363-8f5dc8f1e4ba.png)

**Comment by larswik** [comment]
Yielding support:
![image](https://user-images.githubusercontent.com/25506404/159010985-2a757483-47eb-4fb9-a363-8f5dc8f1e4ba.png)

**Comment by larswik** [comment]
IfcWall/RETAININGWALL seems ok.

Yielding supports:
- Proposal from meeting with domain team 2022-03-18: Yielding supports could be a "Yielding" property on an Arch or Wall. 

Liner plates
- IfcPlate.

Lagging 
- Still not clear.

**Comment by larswik** [comment]
![image](https://user-images.githubusercontent.com/25506404/159479334-c39ff93c-eb14-4a3a-9e90-f7751fb5368f.png)

**Comment by larswik** [comment]
![image](https://user-images.githubusercontent.com/25506404/159479413-7690cf14-de1f-4ffc-80ab-c2d94289db74.png)

**Comment by larswik** [comment]
Proposal:
Liner plates - IfcPlate/?
Lagging - IfcPlate/LAGGING
Yielding supports - A property (HasYieldingSupport : IfcBoolean, YieldingLength:IfcLengthMeasure) connected to any element that can have this (IfcArch and IfcWall were mentioned). Jan Erik states that “I think we agreed that yielding could be a property on all rock support (?) Rock support bolts could be yielding as well”
One possible option is to have this property in a Pset on IfcBuiltSystem/TUNNEL_LINING level?
