### ISSUE TITLE
[IFC Tunnel][Excavation] Hose/tube/... for tunnel support

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#365]
From Jan Erik:
Do we need this a separate rock support item or is bolt enough? – I think we need this as a separate rock support item, or?
This should cover items like 
•	Petroleum tubes
•	Injection tubes
•	Sealing hose
•	Bullflex
 
What term do you prefer?
Tube, pipe or hose?
Do we have two-three main types of this “tubes” to suggest?
**Input needed from domain team!**

**Comment by JanErikHoel** [comment]
Comments from the domain team:

Concerning tube/pipe/hose issue: it depends on the function. We can distinguish:
•	on the one hand tubes that are used for their mechanical properties (petroleum tubes for umbrella vault for example) that are rigid,
•	on the other hand, hoses used to transport a fluid (resin, mortar, grout) that are flexible.
These are 2 kinds of objects.

Bullflex is e very specific use and I don’t know if we have to implement it.


---


Petroleum tubes are pipes generally (tubes have thinner walls)
Injection tubes are not reinforcement, ancillary to grouting
Sealing hoses and Bullflex are also not reinforcement, but ancillary to various supports like arches, liner plates, lagging etc

Tube, pipe or hose are all different, tubes are twin walled pipes, hoses are flexible, generally we use pipes for reinforcing elements, but Swellex anchors are tubes

**Comment by larswik** [comment]
Current model (see also #367)
![image](https://user-images.githubusercontent.com/25506404/159013303-3931b138-1fcc-4333-9a18-de5c633bbee2.png)

**Comment by larswik** [comment]
Proposal: 
- Keep only ROCKSUPPORTBOLT and SPILINGBOLT
- Move TUBE to IfcDiscreteAccessory/STRUCTURAL_SEALING
