### ISSUE TITLE
[IFC Tunnel][Excavation] Service gallery

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#366]
We need an IFC mapping for this.
Definition from domain group: "A spatial zone used to house public and also electrical and mechanical facilities such as drainage pipes, fire mains, power supply and control systems within a facility, so that part of the daily maintenance work can be carried out at the same time as the operation."
- IfcFacilityPart?
- IfcSpace?
- IfcSpatialZone?

See also #359, #360 and especially #372

**Comment by larswik** [comment]
Proposal from #372:
Service gallery : new IfcSpatialZoneTypeEnum - SERVICE_GALLERY or more generic

**Comment by anborr** [comment]
IfcSpatialZone
IfcSpatialZoneTypeEnum : new enum SERVICE_SPACE

**Comment by larswik** [comment]
Proposal to just call it SERVICE
