### ISSUE TITLE
[IFC Tunnel][Excavation] Bolt types

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#367]
We have specified a new entity IfcGroundReinforcementElement with two predefined bolt types ROCKSUPPORTBOLT and SPILINGBOLT. Are these enough? 
**Input from domain team is needed.**

**Comment by JanErikHoel** [comment]
Suggested additional type property

- Solid bar
- Hollow bar (hole < ½ diameter…)
- Tubes/Pipe 
- Cable
- Wire

And in addition an anchor property:
True/False
Enum of anchor type?

And maybe an injection property:
True/False
Enum of injection type?

**Comment by larswik** [comment]
Current model:
![image](https://user-images.githubusercontent.com/25506404/159013161-b9e922e8-3c81-42bb-af53-9d8086eced33.png)
SPILINGBOLT => SPILE
ROCKSUPPORTBOLT => BOLT
Remove TUBE
Add proper definitions!
