### ISSUE TITLE
[IFC Tunnel][Systems] Fire fighting

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#369]
When googling, one can find active fire protection and passive fire protection where active fire protection is about detecting, stopping and escaping fire (e.g. smoke or heat detection, sprinklers, fire hydrants etc) and passive fire protection means containing the fire and preventing it from spreading further (e.g. fire walls, doors).
- Is “firefighting” synonymous to active/passive fire protection?
- Fire fighting as described in the taxonomy seems to cover mostly the “active fire protection” parts, except the “escaping” which seems to be covered more inside the Safety block (sound system, signage etc). Is the “passive” part somewhat captured inside the Safety block as well? There are things like doors in there.
- Would it be interesting to capture both active and passive fire protection as groupings of elements into systems?

**Comment by larswik** [comment]
Proposal:
Re-use IfcDistributionSystem/FIREPROTECTION but generalize the definition slightly.
Current definition: Fire protection sprinkler system.
Proposed definition: Active fire protection for detecting, stopping and escaping fire

Regarding passive fire protection (containing fire and preventing it from spreading further): This sounds more like IfcSpatialZone/FIRESAFETY.

**Comment by anborr** [comment]
Active: I agree with IfcDistributionSystem/FIREPROTECTION 
Passive: IfcBuiltSystem/FIREPROTECTION

**Comment by larswik** [comment]
Decision 2022-03-24:
- Active fire protection
  - Re-use IfcDistributionSystem/FIREPROTECTION (new definition: Active fire protection for detecting, stopping and excaping fire)
- Passive fire protection
  - New PDT IfcBuiltSystem/FIREPROTECTION (definition: Passive fire protection for containing the fire and preventing it from spreading further)
