### ISSUE TITLE
Associating a material to an IfcEarthworksCut

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Specification#37]
IfcRelAssociatesMaterial has a where rule
NoVoidElement : SIZEOF(QUERY(temp <* SELF\IfcRelAssociates.RelatedObjects |
('IFCPRODUCTEXTENSION.IfcFeatureElementSubtraction' IN TYPEOF(temp)) OR
('IFCPRODUCTEXTENSION.IfcVirtualElement' IN TYPEOF(temp))
)) = 0;

This means we can't associate a material for an IfcEarthworksCut element.  Can we adjust the rule so this is permitted?
It could be changed to explicitly mention IfcOpeningElement and IfcVoidingFeature instead of IfcFeatureElementSubtraction

**Comment by SergejMuhic** [comment]
Resolved as stratum having the material. Unit test to follow (says @jmirtsch ).

**Comment by AlexBrad1eyCT** [comment]
Agree, should we close??
