### ISSUE TITLE
[IFC Tunnel][Geotechnics] Keep the distinction between IfcGeoSlice and IfcGeomodel?

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#371]
Nick is keen on keeping the distinction between GeoSlice (2D) and GeoModel (3D) for geotechnics.
One option in the current proposal would be to keep the PredefinedType attribute on IfcGeoScienceModel and add subtypes. If this works, how could these types be named (IFC 4.3 names: IfcGeoslice and IfcGeomodel)?

**Comment by larswik** [comment]
The required model from the domain team where having the typing depending on topic rather than geometric dimension doesn't fit well with the existing IFC schema.
One option for keeping at least the slice would be to add IfcGeoSlice as subclass to IfcGeoScienceModel with the dimensionality restriction. Adding IfcGeoModel as a subclass to IfcGeoScienceModel does not feel very useful.
Still to be resolved.

**Comment by larswik** [comment]
IFC Tunnel project proposes to deprecate the structure based on geometrical dimension in favor of the proposal from the geoscience domain team based on geoscience topic.

**Comment by larswik** [comment]
The outcome of this issue (deprecation) has not yet been implemented. Reopening until this has been done. See also https://github.com/bSI-InfraRoom/IFC-Specification/issues/395

**Comment by AlexBrad1eyCT** [comment]
I am not against deprecation, if a suitable alternative is available, I assume the geotechnical team has taken a full view (all infrastrucutre) of the geotechnical requirements not just the tunnel. in the case of deprecation ALL properties in related property Sets MUST be mapped to the new model setup, as all the properties currently present were deemed required and relevent and cannot be arbitrarily removed.

**Comment by pjanck** [comment]
This seems resolved through #651
