### ISSUE TITLE
[IFC Tunnel][Excavation] Tunnel waterproofing - Cut off not defined in domain taxonomy

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#377]
"Cut off" is defined as a waterproofing element. However it is not defined in the taxonomy or mentioned in the RAR.
**Refer to domain team.**

**Comment by JanErikHoel** [comment]
I found this in the RAR:
![image](https://user-images.githubusercontent.com/48426749/158946893-474a4495-800b-48cd-95fb-16478fc3f773.png)

But it is probably not relevant - I suggest to just forget this.

**Comment by larswik** [comment]
Issue was resolved by adding the following:
- IfcSpatialZone/COMPARTMENT - to handle the tunnel compartments achieved between the cut-offs
- IfcDiscreteAccessory/WATER_BARRIER - to handle the actual cut-offs

Some good definitions for these will be needed!
