### ISSUE TITLE
[IFC Tunnel] Rename IfcReinforcedSoil to IfcGroundImprovementElement and add PDTs

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#384]
We added IfcGroundImprovementElement/LATERALLYDRAINED. 
By that this issue seems resolved.

_Originally posted by @larswik in https://github.com/bSI-InfraRoom/IFC-Specification/issues/376#issuecomment-1094802157_

**Comment by larswik** [comment]
New PDTs:
- DEEPMIXED
- LATERALLYDRAINED
- FROZEN

**Comment by pjanck** [comment]
Resolved through #446
