### ISSUE TITLE
[IFC Tunnel] New/modified entities for excavation

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#386]
Add abstract entity IfcExcavation
Definition: The resulting void from modification of existing terrain or road structure by excavation or by other means of removing material.
NOTE Definition from ISO 6707-1: void that results from bulk excavation of material.
NOTE The material excavated and either used as fill or discarded as waste is not modelled as Cut, but may be handled as a different concept (Resource) in the future. 

Modify IfcEarthworksCut (subclass of IfcExcavation).
Add PDTs:
- CONFINEDOPENEXCAVATION : An open slope excavation where the sides are vertical or near vertical
- ANCHOREDOPENEXCAVATION : A confined open excavation where the vertical walls are anchored. 
- BRACEDOPENEXCAVATION : A confined open excavation where the vertical walls are braced. 

Add entity IfcUndergroundExcavation.
Definition: The resulting void from an underground excavation where the uppermost terrain surface is not affected
PDTs:
- FACEEXCAVATION : A longitudinal underground excavation either of the full face or parts of the full face.
- RADIALEXCAVATION : A lateral underground excavation where the tunnel profile is changed, e.g. widened..

**Comment by pjanck** [comment]
Resolved through #444
