### ISSUE TITLE
[IFC Tunnel] New PredefinedTypes for IfcSpatialZone

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#387]
See 
#358
#360
#366 
#372
Definitions may need some love...
- MAPPEDZONE : A spatial zone used for collecting and recording observations of different kinds.
- TESTEDZONE : A limited zone subjected to in situ tests. Space to carry the related information on test results, methodology and other metadata. Used similar to sample, but for In-situ test
- COMPARTMENT : A tunnel compartment achieved by cut-offs  
- ANNULARGAP : Clearance between excavated surface and lining in tunneling
- CLEARANCE : <<ToDo: Definition>>
- INSTALLATION : Space used for installations, e.g. electrical, ventilation
- INTERIOR : Available space in a tunnel when lining has been installed
- INVERT : The lowest section of a tunnel (floor space)
- LINING : The space in a tunnel used for lining
- SERVICE : Space for e.g. a service gallery in a tunnel

**Comment by pjanck** [comment]
Resolved through #443
