### ISSUE TITLE
[IFC Tunnel] New PDTs for IfcDiscreteAccessory

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#388]
Issue was resolved by adding the following:
- IfcSpatialZone/COMPARTMENT - to handle the tunnel compartments achieved between the cut-offs
- IfcDiscreteAccessory/WATER_BARRIER - to handle the actual cut-offs

Some good definitions for these will be needed!

_Originally posted by @larswik in https://github.com/bSI-InfraRoom/IFC-Specification/issues/377#issuecomment-1094800068_
See also #365

**Comment by larswik** [comment]
- WATER_BARRIER : A device aiding in compartmentalization of water in e.g. tunneling
- STRUCTURAL_SEALING : <<ToDo: Definition>>

**Comment by larswik** [comment]
One possible definition for STRUCTURAL_SEALING from googling: "A sealing capable of transferring either dynamic or static loads (or both)"

**Comment by pjanck** [comment]
Resolved through #442
