### ISSUE TITLE
IfcRelInterferesElements new usage in IFC Infra project

### ISSUE THREAD

**Issue by MatthieuPERIN** [bSI-InfraRoom/IFC-Specification#39]
This issue is to track discussion about the update usage of [IfcRelInterferesElements](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC3/HTML/schema/ifcproductextension/lexical/ifcrelinterfereselements.htm) for IFC Infra project:

*   Link between [IfcSpatialElement](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC3/HTML/schema/ifcproductextension/lexical/ifcspatialelement.htm) as a mean to describe interaction between Spatial structure
*   Evaluate need for [IfcSpatialElement](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC3/HTML/schema/ifcproductextension/lexical/ifcspatialelement.htm) x [IfcElement](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC3/HTML/schema/ifcproductextension/lexical/ifcelement.htm) relation
*   Update documentation to clarify Relation properties in these new context

Proposed `InterferencesTypes` are : " Crosses", "PassesThrough", "PassesOver", "PassesUnder", "Clash", "Along"

**Comment by MatthieuPERIN** [comment]
First draft proposed in draft merge request #40

**Comment by AlexBrad1eyCT** [comment]
In relation to above I am of the opinion that there is no use case currently for spatial to physical interference therefore some restriction (informal or formal) is required to to restrict this cross interference.

As far as everything else the related pull request covers 90% of the expected cases and guidance on encoding.

**Comment by MatthieuPERIN** [comment]
There is an use case in Rail: interactions between the footprint of a railway (`IfcRailway`) and existing / designed drainage system (`IfcProduct`)

This Unit test (UT\_RSS3) was postpone to Storyline test because of the work on `IfcRelInterferesElements`(Chicken-and-egg issue).

Overview of the data structure (without interactions):
![](https://user-images.githubusercontent.com/4550257/119503117-e9b3f480-bd6a-11eb-936a-1ee78edc7f24.png)

**Comment by MatthieuPERIN** [comment]
Comment by @SergejMuhic in #40 copied here to be discussed:

> Spatial structure elements are not supposed to intersect. That is kind of their purpose, reserving space. If subtracting anything, does the dataset have to feature the subtracted geometry, or are both elements supposed to have original geometry (e.g. IfcRelVoidsElement)?

To me two point here:

1.  The Spatial Structure Element intersecting issue
2.  The substracted geometry / IfcRelVoidsElement

**Comment by MatthieuPERIN** [comment]
Comment on point 2 above:

The updated documentation is just a reformulation of the old one about the subtraction of geometry. I think that we should stick to the usage of `IfcRelVoidsElement` and state that the geometry should remain complete.

**Comment by MatthieuPERIN** [comment]
Comment on point 1 above:

*   The spatial structure are defined in the [documentation](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC3/HTML/link/ifcspatialstructureelement.htm) as "organizing structure" without any physical/geometrical regulation (as their shape are optional).
*   The traditional usage of these concepts in Building description imply non spatial overlapping (buildings / storey description)
*   Infra stakeholder will need to have overlapping structural description for their project as for example a railway level crossing is an area part of the road structure and the rail structure altogether.

I propose therefor to release the usage rules about preventing spatial structure overlapping, 

Nevertheless, some misleading and ineffective spatial decomposition may then exists (e.g:  a spatial element holding all the sleepers and another for the rails) if we do not provide "usage ruels", I propose to add an explicit statement to prevent that:

1.  The spatial project structure, established by the IfcRelAggregates, shall be acyclic. (existing rule in documentation)
2.  At the exception of shared area where several infrastructures meet, the spatial structure elements should not overlap with each other.

These rules may be added to IfcRElInterfers documentation and maybe updated in IfcSpatialStructureElement ?

**Comment by larswik** [comment]
On Issue 1: The use of IfcRelInterferesElement for spatial structure elements was agreed on already in the Infra/Rail harmonization meeting in Stockholm mid September 2019 as a replacement for the previously proposed new relationship type (I don't remember the exact name) derived from Stakeholder requirements. 
Options:
1. Leave as proposed
2. Find an alternative solution if the current proposal is not allowed. 
3. Delete this option from schema and accept this as a gap between stakeholder's requirements and schema put in the backlog
I would put my personal vote on 1 or 3.

**Comment by MatthieuPERIN** [comment]
Solution to be implemented, follow in #111  
 

![](https://user-images.githubusercontent.com/4550257/124091071-bc3b2480-da55-11eb-9f2b-078480efcbc9.png)
