### ISSUE TITLE
[IFC Tunnel] Add PredefinedType LAGGING for IfcPlate

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#390]
Proposal:
Liner plates - IfcPlate/?
Lagging - IfcPlate/LAGGING
Yielding supports - A property (HasYieldingSupport : IfcBoolean, YieldingLength:IfcLengthMeasure) connected to any element that can have this (IfcArch and IfcWall were mentioned). Jan Erik states that “I think we agreed that yielding could be a property on all rock support (?) Rock support bolts could be yielding as well”
One possible option is to have this property in a Pset on IfcBuiltSystem/TUNNEL_LINING level?

_Originally posted by @larswik in https://github.com/bSI-InfraRoom/IFC-Specification/issues/364#issuecomment-1094961662_

**Comment by larswik** [comment]
New PDT IfcPlate/LAGGING : Provide definition.

**Comment by larswik** [comment]
Found this definition from googling: "Lagging is the structural material (most often wood) that spans the distance between spars at an excavation site. Lagging, and the steel spars they connect to, provides temporary ground support as a safety measure during tunneling. The lagging is installed horizontally between vertically installed spars."

**Comment by pjanck** [comment]
Resolved through #441
