### ISSUE TITLE
[IFC Tunnel] Add mechanism for external datasets

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#392]
Indeed, we think that this is the right approach for geophysical surveys or similar extensive data sets represented by Voxel models

_Originally posted by @j-weil in https://github.com/bSI-InfraRoom/IFC-Specification/issues/316#issuecomment-1064010739_

**Comment by larswik** [comment]
Add IfcDatasetReference entity as subtype of IfcExternalReference.
Attributes: 
- Filter : Optional IfcText
- ReferencedDataset : Optional IfcDatasetInformation

New entity IfcDatasetInformation subtype of IfcExternalInformation (or IfcDocumentInformation?)
Attributes:
- Same as IfcDocumentInformation + SchemaReference : Optional IfcLabel (or IfcURIReference?)

Add entity IfcRelAssociatesDataset subtype of IfcRelAssociates
Attributes:
- RelatingDataset : SELECT (IfcDatasetReference | IfcDatasetInformation)

**Comment by pjanck** [comment]
Resolved through #427
