### ISSUE TITLE
[IFC Tunnel] Add tunnel facility

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#397]
IfcTunnel : Subtype of IfcFacility
PDTs:
- ACCESSTUNNEL : Passage from surface to areas of underground excavation
- SHAFT : an underground vertical or inclined passageway
- UTILITIES : A tunnel built for utilities such as water, gas or high voltage transmission.
- RAILWAY : A tunnel mainly built for railway traffic.
- ROAD : A tunnel mainly built for road traffic.
- PEDESTRIAN : A tunnel mainly built for pedestrians.
- METRO : A tunnel mainly built for metro traffic.
- BICYCLE : A tunnel mainly built for bicycle traffic.
- BYPASS : <<ToDo definition>> "A secondary tunnel to allow a flow when the main tunnel is closed or blocked."??
- MAINTENANCE : A tunnel mainly built to enable tunnel maintenance.
- UNDERGROUND_FACILITIES : A tunnel mainly built for other underground facilities.
- RAMP : A tunnel connecting tunnels at different levels or a tunnel with the above ground

**Comment by pjanck** [comment]
Resolved through #450
