### ISSUE TITLE
[IFC Tunnel] New PDTs for IfcElementAssembly

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#400]
- DUCTBANK : A Duct Bank is two or more ducts or conduits used as part of a system. A duct bank is designed to protect and group or consolidate data and electrical cables to and from a facility. The cables are laid in PVC pipes or conduits. These conduit are bundled together and protected with either steel or reinforced concrete casings. Duct banks are often located underground. They can carry cables for all electrical wiring and data requirements in the facility as well as extra cables that are not for immediate use, but may be valuable for future requirements.
- UMBRELLAVAULT : A set of boreholes armed with high inertia tubes resting, on the one hand, on the advancement core (part of the ground not yet excavated at the front) and on the other hand, on a rigid support, placed behind the face.

**Comment by pjanck** [comment]
Resolved through #433
