### ISSUE TITLE
[IFC Tunnel] [Geotechnics] Settle domain input regarding GeotechSynthesisModel and GeoHazardModel

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#407]
> _GeotechSynthesisModel and GeoHazardModel seems to have been removed. Is this "by design"?_
> 
> No, we would like them retained. They need to be defined with the help of the Excavation and Support team.

Ok, we'll need to come back to this then!

_Originally posted by @larswik in https://github.com/bSI-InfraRoom/IFC-Specification/issues/373#issuecomment-1094820678_

**Comment by larswik** [comment]
GeotechSynthesisModel and GeoGazardModel are both proposed as PDTs of IfcGeoScienceModel.
According to mail-discussions, a GeotechSynthesisModel contains GeotechTypicalSection elements which are essentially longitudinal sections along the alignment with homogeneous properties. The proposal from the tech team would be to implement GeotechTypicalSection as a kind of IfcLinearElement which can be positioned relative to two IfcReferent (positioned along the alignment), a from- and a to referent.
The only concrete element so far for GeoHazardModel is HazardArea which is modeled as an  IfcGeoScienceFeature/HAZARDAREA.
Principles for "longitudinal sections":
![image](https://user-images.githubusercontent.com/25506404/169466358-4a2f0608-03f8-4f3f-8e0a-d32f96cf2c89.png)

![image](https://user-images.githubusercontent.com/25506404/169466433-ce17bdf6-f512-43b6-9def-f321eac8b5a3.png)

**Comment by j-weil** [comment]
Geometry of GeotechTypicalSection: the IfcLinearElement that correspond via the common reference to the alignment are a good solution. 
Additional Psets can be added to cover different requirements, e.g. risks (see image below) option There are additional needs to have volumetric representation in places, like extrusions or sweeps with different diameters or cross sections.
![image](https://user-images.githubusercontent.com/49076658/172871455-5a9ea927-8761-4a7b-88e1-e300491bc971.png)

**Comment by larswik** [comment]
Connected to issue #447

**Comment by mbeaufils** [comment]
> GeotechSynthesisModel and GeoGazardModel are both proposed as PDTs of IfcGeoScienceModel. 

Agree

> According to mail-discussions, a GeotechSynthesisModel contains GeotechTypicalSection elements which are essentially longitudinal sections along the alignment with homogeneous properties. 

Also what I have in mind.

> The proposal from the tech team would be to implement GeotechTypicalSection as a kind of IfcLinearElement which can be positioned relative to two IfcReferent (positioned along the alignment), a from- and a to referent. 

Does this mean a GeotechTypicalSection can only be represented as "line(s)" ?

**Comment by larswik** [comment]
There is so far no requirement that a GeotechTypicalSection (IfcLinearElement) is represented by only a line geometrically. It is an IfcProduct and, as such, may have any geometric representation. However, one of its main characteristics is that it is located along a longitudinal portion of the tunnel alignment and one option could even be to have no explicit geometry at all (in addition to the definition of from-to along the alignment). 

One the other hand, as of right now, there is nothing that I know of that prevents any IfcProduct to be located along the alignment in a similar fashion. Maybe this has to be fine-tuned during a deployment phase?
