### ISSUE TITLE
[IFC Tunnel] Definition of IfcDatasetInformation (or just reuse IfcDocumentInformation) in support of IfcDatasetReference (metadata definition)

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#411]
Thanks @billeast. Good to have that requirement logged here. Please log any related requirements here as well. I think that the aim for this functionality is to add it to the IfcExternalReferenceResource part of the IFC schema (same as e.g. IfcClassificationReference, IfcDocumentReference, IfcLibraryReference etc) which means that it must provide a generic mechanism. When finalized, the proposal therefore needs to be reviewed also by experts outside of the IFC Tunnel project. I also add the link to the standard [ISO 21597-1:2020](https://www.iso.org/standard/74389.html) which might provide relevant input.

_Originally posted by @larswik in https://github.com/bSI-InfraRoom/IFC-Specification/issues/316#issuecomment-1063756231_

**Comment by larswik** [comment]
Personally, I would subtype IfcDocumentInformation and possibly add one attribute _SchemaReference : IfcURIReference_

**Comment by anborr** [comment]
> Personally, I would subtype IfcDocumentInformation and possibly add one attribute _SchemaReference : IfcURIReference_

D'accord.
