### ISSUE TITLE
Add capability to reference external datasets from IFC objects

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#424]
> Personally, I would subtype IfcDocumentInformation and possibly add one attribute _SchemaReference : IfcURIReference_

D'accord.

_Originally posted by @anborr in https://github.com/bSI-InfraRoom/IFC-Specification/issues/411#issuecomment-1134819130_

As a parallel structure to e.g. IfcDocumentReference...

New ENTITY IfcDatasetReference : Subtype of IfcExternalReference
- Filter : OPTIONAL IfcText : An optional text as e.g. SQL, XQuery etc to filter out data when only a subset is relevant for the dataset reference.

New ENTITY IfcDatasetInformation : Subtype of IfcDocumentInformation
- SchemaReference : OPTIONAL IfcURIReference : An optional reference to a schema (e.g. xsd) describing the structure of the referenced document

New Type IfcDatasetSelect : SELECT (IfcDatasetReference,IfcDatasetInformation)

New ENTITY IfcRelAssociatesDataset
- RelatingDataset : IfcDatasetSelect : Dataset information or reference which is applied to the objects.

**Comment by larswik** [comment]
![image](https://user-images.githubusercontent.com/25506404/170002658-cbb0e722-9896-44c0-9ff1-8e16a3ff6467.png)

**Comment by pjanck** [comment]
Resolved through #427
