### ISSUE TITLE
[IFC Tunnel]IfcLinearStructureElement and IfcLinearZone as subtypes of IfcLinearElement - IfcGeotechTypicalSection as subtype of IfcLinearZone

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#447]
A "Parallel" structure to the spatial structure for linearly oriented infrastructure data
The current IfcAlignment entities shall be subtyped from IfcLinearStructureElement where elements of the same type shall not overlap linearly. Similar to a spatial zone, the linear zones are not as rigid, but defines arbitrary linear zones along an alignment which can be used for locating entities linearly. One example of a "linear zone" is a "GeotechTypicalSection" (see issue #407), which describes an interval along the alignment/building structure with similar ground conditions, as part of the GeotechSynthesis model that represents the connection between the ground model and the building. This includes key-properties like expected distribution of ground types (reference to GeotechUnits) and baseline-definition of expected ground conditions and potential hazards, and may also include key-information on design like excavation measures, distribution of support types etc.

**Comment by larswik** [comment]
To avoid "latency" due to PR dependency, Also add the IfcGeotechTypicalSection entity here.
Subtype of IfcLinearZone.
Description: Interval along the alignment/building structure with similar ground conditions, as part of the GeotechSynthesis model that represents the connection between the ground model and the building. Includes key-properties like expected distribution of ground types (reference to GeotechUnits) and baseline-definition of expected ground conditions and potential hazards, and may also include key-information on design like excavation measures, distribution of support types etc.
PredefinedType : IfcGeotechTypicalSectionTypeEnum {USERDEFINED | NOTDEFINED]

**Comment by j-weil** [comment]
Hi Lars,
as discussed today we propose to change the Entity IfcGeotechTypicalSection https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/ to cover the same concept more generally for tunnel design, and call it e.g. IfcTunnelTypicalSection.
PDTs can then cover both Geotechnics, tunnel design and related risks, as described earlier e.g. in image below.
PDT "GeotechTypicalSection"
PDT "ExcavationSupportSection"
PDT "RiskSection"

This would allow to apply the concept to many other design-relevant aspects and create user defined PDTs

![image](https://user-images.githubusercontent.com/49076658/196911546-4b651ac1-6ef9-47f2-a964-f6105cfc76dc.png)

**Comment by SergejMuhic** [comment]
This issue was closed. I will create a new issue for this.

**Comment by pjanck** [comment]
> This issue was closed. I will create a new issue for this.

Superseded by #482.
