### ISSUE TITLE
[IFC Tunnel] Add IfcVoxelGrid

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#449]
IfcVoxelGrid : subtype of IfcTesselatedItem (probably - some foreseen changes where IfcTesselatedFaceSet.HasColours could be moved to IfcTtesselatedItem)
VoxelSizeX : IfcNonNegativeLengthMeasure (size of voxels in x)
VoxelSizeY : IfcNonNegativeLengthMeasure (size of voxels in y)
VoxelSizeZ : IfcNonNegativeLengthMeasure (size of voxels in z)
GridSizeX : IfcInteger (number of voxels along x)
GridSizeY : IfcInteger (number of voxels along y)
GridSizeZ : IfcInteger (number of voxels along z)
Voxels : Array 1:? of IfcBoolean (array size = GridSizeX * GridSizeY * GridSize Z. Indicates whether voxel is "filled" or not)

**Comment by larswik** [comment]
Will be fixed by #329.

**Comment by pjanck** [comment]
Fixed by #329
