### ISSUE TITLE
[IFC Tunnel]IfcLinearStructureElement rename IfcGeotechnicalTypicalSection to IfcTunnelTypicalSection

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#482]
Hi Lars,
as discussed today we propose to change the Entity IfcGeotechTypicalSection https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/ to cover the same concept more generally for tunnel design, and call it e.g. IfcTunnelTypicalSection.
PDTs can then cover both Geotechnics, tunnel design and related risks, as described earlier e.g. in image below.
PDT "GeotechTypicalSection"
PDT "ExcavationSupportSection"
PDT "RiskSection"

This would allow to apply the concept to many other design-relevant aspects and create user defined PDTs

![image](https://user-images.githubusercontent.com/49076658/196911546-4b651ac1-6ef9-47f2-a964-f6105cfc76dc.png)

_Originally posted by @j-weil in https://github.com/bSI-InfraRoom/IFC-Specification/issues/447#issuecomment-1285225031_

**Comment by SergejMuhic** [comment]
Pinging [j-weil](https://github.com/j-weil)

**Comment by j-weil** [comment]
Great, Thanks Sergej

Von: SergejMuhic ***@***.***>
Gesendet: Donnerstag, 20. Oktober 2022 11:36 Uhr
An: bSI-InfraRoom/IFC-Specification ***@***.***>
Cc: Jonas WEIL ***@***.***>; Mention ***@***.***>
Betreff: Re: [bSI-InfraRoom/IFC-Specification] [IFC Tunnel]IfcLinearStructureElement rename IfcGeotechnicalTypicalSection to IfcTunnelTypicalSection (Issue #482)


Pinging j-weil<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fj-weil&data=05%7C01%7Cj.weil%40ic-group.org%7C8174195ff08a493fbed508dab27e8ff2%7Cf90b19c709eb433b83531cd1745e4202%7C0%7C0%7C638018553898980620%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9vK9OtGxfp6wuPcnMc2xTcppcsv0fqnWJAOPJ0fyGz4%3D&reserved=0>

-

**Comment by larswik** [comment]
I agree with this. It was also discussed together with the Excavation team that was also onboard with this.
One issue could maybe be that there could be a need to link, e.g. an IfcTunnelSection/SUPPORTSECTION (design information) with e.g. an IfcElementAssembly/ARCH or IfcArchElement (as-built). Could IfcRelAssignsToProduct be used for this? See also the following issues:
- #483
- #484
