### ISSUE TITLE
[IFC Tunnel] Add IfcArchElement and IfcArchElementType

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#486]
These seem to have been forgotten during the previous IFC Tunnel extension session.
ENTITY IfcArchElement
SUBTYPE OF IfcBuiltElement
Definition: A unitary curved structure.

ENTITY IfcArchElementType
SUBTYPE of  IfcBuiltElementType
Definition: The element type IfcArchElementType defines commonly shared information for occurrences of arch elements.

And the usual CorrectPredefinedType/CorrectTypeAssigned (Only USERDEFINED and NOTDEFINED as of yet)

**Comment by pjanck** [comment]
Resolved through #490
