### ISSUE TITLE
IfcVoxelData indeterminate array bounds not allowed

### ISSUE THREAD

**Issue by aothms** [bSI-InfraRoom/IFC-Specification#492]
Purely technical issue outside of the bigger discussion on voxels in general:

```
ENTITY IfcIntegerVoxelData
 SUBTYPE OF (IfcVoxelData);
	Values : ARRAY [1:?] OF IfcInteger;
	Unit : OPTIONAL IfcUnit;
END_ENTITY;
```

> *8.2 Aggregation data types*
>
> An `array` is a fixed-size ordered collection. It is indexed by a sequence of integers.

or if we fast forward to 8.2.1 more explicitly:

> *8.2.1 Array data type*
> 
> ...
>
> NOTE 1 The bounds may be positive, negative or zero, but may not be indeterminate (`?`) (see 14.2).

**Comment by larswik** [comment]
What about changing it to a LIST instead?

**Comment by TLiebich** [comment]
Not sure about the intended semantics, but in my view an array is only necessary if the indexing number needs to be controlled, like ARRAY[10:12] meaning a fixed ordered collections of 3 items, addressed by [10], [11], [12] or if intermediate NIL values needs to be allowed (sparse), i.e. [10] -> "1", [11] -> NIL, [12] -> "3"

so in most cases, LIST is the better option.

**Comment by larswik** [comment]
In this case there are more than one array/list to iterate simultaneously so LIST could be slightly more tedious but since ARRAY doesn't allow for indeterminate boundaries...

**Comment by SergejMuhic** [comment]
> In this case there are more than one array/list to iterate simultaneously so LIST could be slightly more tedious but since ARRAY doesn't allow for indeterminate boundaries...

I think LIST fits wonderfully. ARRAY is definitely not the data structure to go for. I don't think I understood why there would be " more than one array/list to iterate simultaneously". Could you elaborate on that?

**Comment by larswik** [comment]
> > In this case there are more than one array/list to iterate simultaneously so LIST could be slightly more tedious but since ARRAY doesn't allow for indeterminate boundaries...
> 
> I think LIST fits wonderfully. ARRAY is definitely not the data structure to go for. I don't think I understood why there would be " more than one array/list to iterate simultaneously". Could you elaborate on that?

IfcVoxelData + IfcVoxelGrid

**Comment by SergejMuhic** [comment]
Why would it be more tedious though? That is the part I can' get my head around, What is the difference between ARRAY and LIST chosen for `Values`. I see the same iteration honestly.

**Comment by larswik** [comment]
> Why would it be more tedious though? That is the part I can' get my head around, What is the difference between ARRAY and LIST chosen for `Values`. I see the same iteration honestly.

If you say so I will not argue.

**Comment by SergejMuhic** [comment]
LIST elements are accessed by their position if this was your concern.

**Comment by aothms** [comment]
What I recall from previous discussions with you was that there was a desire to express missing data. Maybe that was a concern? For that you'd have to also change the type to `ARRAY [1:n] OF OPTIONAL IfcInteger;`. If you really want an array it's possible as a derived attribute:

```
ENTITY IfcIntegerVoxelData
 SUBTYPE OF (IfcVoxelData);
	ValueList : LIST [1:?] OF IfcInteger;
	ValuesPresent : LIST [1:?] OF IfcBoolean;
	Unit : OPTIONAL IfcUnit;
 DERIVE
    Values : ARRAY [1:HIINDEX(SELF.ValueList)] OF OPTIONAL IfcInteger = SomeFunctionThatZipsTheTwoLists()
END_ENTITY;
```

**Comment by SergejMuhic** [comment]
> What I recall from previous discussions with you was that there was a desire to express missing data. Maybe that was a concern? For that you'd have to also change the type to `ARRAY [1:n] OF OPTIONAL IfcInteger;`. If you really want an array it's possible as a derived attribute:
> 
> ```
> ENTITY IfcIntegerVoxelData
>  SUBTYPE OF (IfcVoxelData);
> 	ValueList : LIST [1:?] OF IfcInteger;
> 	ValuesPresent : LIST [1:?] OF IfcBoolean;
> 	Unit : OPTIONAL IfcUnit;
>  DERIVE
>     Values : ARRAY [1:HIINDEX(SELF.ValueList)] OF OPTIONAL IfcInteger = SomeFunctionThatZipsTheTwoLists()
> END_ENTITY;
> ```

Something like IfcMakeArrayOfArray 😄 , but for merging the two collections. Union, full outer join, something like that?

But I would just access the objects from a function and iterate over both by index. No need for additional allocations. I might be way of the actual issue though.

**Comment by larswik** [comment]
IfcVoxelData has the attribute Voxels : LIST [1:?] OF IfcBoolean that indicates which voxels are actually filled. Isn't it then enough with ValueList : LIST [1:?] OF OPTIONAL IfcInteger (corresponding change to all subtypes of IfcVoxelData)?

I.e.:
ENTITY IfcIntegerVoxelData
 SUBTYPE OF (IfcVoxelData);
  Values : LIST [1:?] OF OPTIONAL IfcInteger;
  Unit : OPTIONAL IfcUnit;
END_ENTITY;

If this is ok, I can create a PR and also fix #499 at the same time.

**Comment by larswik** [comment]
Ping @SergejMuhic and @aothms

**Comment by SergejMuhic** [comment]
`OPTIONAL` is not applicable to `LIST.` Not sure if a list can hold indeterminate values.

I see two options:
1. Not sure about this one.
 ```
ENTITY IfcIntegerVoxelData
 SUBTYPE OF (IfcVoxelData);
        GridSize : IfcInteger;
	Values : ARRAY [0:GridSize - 1] OF IfcInteger;
	Unit : OPTIONAL IfcUnit;
END_ENTITY;
```
2. Use `FUNCTION IfcListToArray(Lis : LIST [0:?] OF GENERIC : T;Low,U : INTEGER) : ARRAY OF GENERIC : T;`
```
ENTITY IfcIntegerVoxelData
 SUBTYPE OF (IfcVoxelData);
        GridSize : IfcInteger;
	Values : LIST [1:?] OF IfcInteger;
	Unit : OPTIONAL IfcUnit;
  DERIVED:
        ValuesAsArray : ARRAY [0:GridSize - 1] OF IfcInteger := IfcListToArray(Values, GridSize);
END_ENTITY
```

Of course we could take it further and get `GridSize` from `IfcVoxelGrid` directly.

**Comment by TLiebich** [comment]
lists cannot have indetermined values, arrays can.
array upper bounds cannot be intetermined (?), but can contain any numeric expression - so ARRAY [0:GridSize 1] is valid. In my view, the use of a derived statement here is not necessary. But if the array shall be allowed to have indetermined values, an optional keyword needs to be added.

```
ENTITY IfcIntegerVoxelData
SUBTYPE OF (IfcVoxelData);
   GridSize : IfcInteger;
   Values : ARRAY [1:GridSize] OF OPTIONAL IfcInteger;
   Unit : OPTIONAL IfcUnit;
END_ENTITY;
```
n.b. everywhere else in IFC aggregates are usually 1-based, not 0-based. To avoid confusions, I would propose to have ARRAY[1: ...]

**Comment by TLiebich** [comment]
also this should be legal

```
ENTITY IfcIntegerVoxelData
SUBTYPE OF (IfcVoxelData);
   Values : ARRAY [1:GridSize] OF OPTIONAL IfcInteger;
   Unit : OPTIONAL IfcUnit;
 DERIVE
   GridSize : IfcInteger := getItFromVoxelGrid(SELF);
END_ENTITY;
```

**Comment by SergejMuhic** [comment]
> lists cannot have indetermined values, arrays can.

Seemed that this is the case. Thanks for confirming / clarifying.



> n.b. everywhere else in IFC aggregates are usually 1-based, not 0-based. To avoid confusions, I would propose to have ARRAY[1: ...]

This certainly makes sense. I would definitely go for this instead of `[ 0 : GridSize ]` then.

**Comment by SergejMuhic** [comment]
```
ENTITY IfcIntegerVoxelData
SUBTYPE OF (IfcVoxelData);
   Values : ARRAY [1:GridSize] OF OPTIONAL IfcInteger;
   Unit : OPTIONAL IfcUnit;
 DERIVE
   GridSize : IfcInteger := SIZEOF(SELF\IfcProduct.Representation.Representations[1].Items[1]\IfcVoxelGrid.Voxels);
 WHERE
   HasRepresentation : EXISTS(SELF\IfcProduct.Representation):
   GeometryIsVoxel : 'IFCVOXELGRID' IN TYPEOF(SELF\IfcProduct.Representation.Representations[1].Items[1]);
END_ENTITY;
```
I would add the two WRs here then.

**Comment by larswik** [comment]
So, can we decide something? 
- Use ARRAY [1:GridSize] OF OPTIONAL IfcInteger
- Getting GridSize from the IfcVoxelGrid. Requires that IfcRelAssignsToProduct.RelatingProduct.Representation etc actually exists.
- Explicitly declare GridSize is redundant but maybe clearer?

**Comment by larswik** [comment]
I propose to remove IfcVoxelData.Name at the same time (see #499).

**Comment by larswik** [comment]
Shall I take care of this or will you @SergejMuhic ?

**Comment by pjanck** [comment]
Ping @larswik and @SergejMuhic : let's get this sorted out before we start with Voxels in the deployment.

**Comment by SergejMuhic** [comment]
PR merged.
