### ISSUE TITLE
IfcVoxelData Name Attribute

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Specification#499]
https://github.com/bSI-InfraRoom/IFC-Specification/blob/95f944646991624619ad3f80fb53793d650319dc/IFC4x3/Sections/Core%20data%20schemas/Schemas/IfcProductExtension/Entities/IfcVoxelData/DocEntity.xml

IfcVoxelData inherits from IfcRoot, but has an explicit attribute Name in both classes.  It's not derived.
This seems wrong and causes a defect in the published documentation (ie attribute 3 is missing in inherited attributes).

https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/

**Comment by larswik** [comment]
Thanks for noticing! I believe that this is a mistake that should be fixed at the same time as fixing #492.
