### ISSUE TITLE
Psets Documentation Road And PortsAndWaterways

### ISSUE THREAD

**Issue by christophe-blt** [bSI-InfraRoom/IFC-Specification#50]
**Missing Documentation on IfcPortsAndWaterways** 

0780f51c-54af-4905-9639-f70a911427bf | Pset_MarineFacilityTransportation
e82c6a00-79da-43db-ae46-6eab6d295bca | Pset_ProjectCommon

**Missing Documentation on Road Psets**
75246832-754b-4570-a4e2-24baa7a30a33 | Pset_BoundedCourseCommon
1b6cb3aa-95e9-4fec-8d1a-d6d502edb484 | Pset_CourseApplicationConditions
0c6dd572-b9b4-424c-94e6-454d24d56fb7 | Pset_KerbCommon
6fa143be-9ee1-451f-94b7-df9b5e8923e3 | Pset_KerbStone
a292e50a-6238-42bf-8cbf-70af606b496c | Pset_MarkingLinesCommon
7ea2803e-b036-441a-b4a2-f99ae69bc57a | Pset_OnSiteCastKerb
b233d75e-d40c-4561-b2de-a7f32d713442 | Pset_PavementMillingCommon
0448238f-e315-43c1-90c1-55ec84720113 | Pset_PavementSurfaceCommon
bff7eedc-8844-446a-b6c2-fd5bdaad0968 | Pset_PlantCommon
7a86e0ed-726f-4b94-aaf9-16197a3501d9 | Pset_PrecastKerbStone
e4d7b2f1-fe81-4317-9f58-629e0825c2e4 | Pset_RadiiKerbStone
e10080b5-0bcc-453a-b230-5c72efe09fb4 | Pset_RoadMarkingCommon
1beaa2e6-a4a1-4d14-a2c7-ba651e6baec6 | Pset_RoadSymbolsCommon
a94cc9f8-5439-4d6c-a557-1732a0e8c427 | Pset_SumpBusterCommon
12089fbe-3ddb-4d69-b5f9-83766de3862d | Pset_TrafficCalmingDeviceCommon
b9eb3ef7-c3c5-4f09-b18b-e53ce14dfd1b | Pset_TransitionSectionCommon
42d4fb02-c215-40ed-bf76-d054beb33ace | Pset_TrenchExcavationCommon

**Comment by AlexBrad1eyCT** [comment]
> 0780f51c-54af-4905-9639-f70a911427bf | Pset_MarineFacilityTransportation
> e82c6a00-79da-43db-ae46-6eab6d295bca | Pset_ProjectCommon

Both documented in pull request #42 under review

**Comment by AlexBrad1eyCT** [comment]
> **Missing Documentation on Road Psets**
> 75246832-754b-4570-a4e2-24baa7a30a33 | Pset_BoundedCourseCommon
> 1b6cb3aa-95e9-4fec-8d1a-d6d502edb484 | Pset_CourseApplicationConditions
> 0c6dd572-b9b4-424c-94e6-454d24d56fb7 | Pset_KerbCommon
> 6fa143be-9ee1-451f-94b7-df9b5e8923e3 | Pset_KerbStone
> a292e50a-6238-42bf-8cbf-70af606b496c | Pset_MarkingLinesCommon
> 7ea2803e-b036-441a-b4a2-f99ae69bc57a | Pset_OnSiteCastKerb
> b233d75e-d40c-4561-b2de-a7f32d713442 | Pset_PavementMillingCommon
> 0448238f-e315-43c1-90c1-55ec84720113 | Pset_PavementSurfaceCommon
> bff7eedc-8844-446a-b6c2-fd5bdaad0968 | Pset_PlantCommon
> 7a86e0ed-726f-4b94-aaf9-16197a3501d9 | Pset_PrecastKerbStone
> e4d7b2f1-fe81-4317-9f58-629e0825c2e4 | Pset_RadiiKerbStone
> e10080b5-0bcc-453a-b230-5c72efe09fb4 | Pset_RoadMarkingCommon
> 1beaa2e6-a4a1-4d14-a2c7-ba651e6baec6 | Pset_RoadSymbolsCommon
> a94cc9f8-5439-4d6c-a557-1732a0e8c427 | Pset_SumpBusterCommon
> 12089fbe-3ddb-4d69-b5f9-83766de3862d | Pset_TrafficCalmingDeviceCommon
> b9eb3ef7-c3c5-4f09-b18b-e53ce14dfd1b | Pset_TransitionSectionCommon
> 42d4fb02-c215-40ed-bf76-d054beb33ace | Pset_TrenchExcavationCommon

Documented and merged per pull request #33
