### ISSUE TITLE
Create CT and GU for "Project Global Positioning Mapped"

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#507]
I am not entirely sure what the difference is between this and the existing "Project Global Positioning"?

**Comment by pjanck** [comment]
See also #495 :)

**Comment by pjanck** [comment]
> what the difference is between this and the existing "Project Global Positioning"?

This one would connect `IfcProjectedCRS` with `IfcRigidOperation` to the `IfcGeometricRepresentationContext`.

**Comment by pjanck** [comment]
Resolved through #508
