### ISSUE TITLE
Express schema <> serialization

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Specification#513]
I notice a couple of where rules serialized incorrectly in the Express schema (in the recent Tunnel schemas).
It uses a ML encoding for <>
Ie 

    HasObjectType : (PredefinedType &lt;&gt; IfcBridgePartTypeEnum.USERDEFINED) OR 

As I understand it (and is typically), should be

    HasObjectType : (PredefinedType <> IfcBridgePartTypeEnum.USERDEFINED) OR 

There are at least two occurrences, worth searching the schema to elminate them all.

EDIT: Markdown syntax - makes the problem pop out.

**Comment by SergejMuhic** [comment]
Hm, this is weird. It should not be encoded in HTM. I will check when this happened. Any other occurrences of this?

**Comment by SergejMuhic** [comment]
@jmirtsch I have put the fix up. Would merge ASAP. If you found any other occurrences let me know. We can do another PR.
