### ISSUE TITLE
Both `XAxisAbscissa` and `XAxisOrdinate` cannot be zero.

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#518]
Both `XAxisAbscissa` and `XAxisOrdinate` cannot be zero.

@larswik @SergejMuhic Should we introduce a `WHERE` rule here?

_Originally posted by @pjanck in https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/61#discussion_r1112700796_

**Comment by larswik** [comment]
I think that we should! And maybe fix this typo at the same time (easting):
"Specifies the value along the **easing** axis of the end point of a vector indicating the position of the local x axis of the engineering coordinate reference system."

**Comment by SergejMuhic** [comment]
Certainly, let us add it.

@larswik that one also caught my attention.

**Comment by larswik** [comment]
Maybe a specification for defaults is needed for when XAxisAbscissa and XAxisOrdinate are omitted as well.

**Comment by SergejMuhic** [comment]
`XAxisAbscissa` = 1.0
`XAxisOrdinate` = 0.0

If not otherwise specified.
