### ISSUE TITLE
Produce "Voxel Geometry" ConceptTemplate

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#524]
For Sprint 2.3 we should define Voxel Geometry ConceptTemplate. Ideas?

**Comment by larswik** [comment]
I guess that this one should be something like:
- Body Geometry
  - Body Voxel Geometry
    - IfcElement=>IfcProductDefinitionShape=>IfcShapeRepresentation[RepresentationIdentifier='Body', RepresentationType='Voxel'?? (new)]=>IfcVoxelGrid

Besides this, there should also be a need for an IfcVoxelData CT. Here, I don't remember if it is the IfcElement (e.g. IfcGeoScienceFeature) or IfcVoxelData that has the voxel representation. In any case the IfcElement and the related IfcVoxelData should be connected through IfcRelAssignsToProduct.

**Comment by pjanck** [comment]
In case we introduce a new `RepresentationType`, we need to adapt the [IfcShapeRepresentationTypes](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/schema/ifcrepresentationresource/lexical/ifcshaperepresentationtypes.htm) function as well.

**Comment by pjanck** [comment]
Closing following #617 and #618 .
