### ISSUE TITLE
IfcAlignmentVerticalSegment.HorizontalLength + IfcAlignmentCantSegment.HorizontalLength

### ISSUE THREAD

**Issue by peterrdf** [bSI-InfraRoom/IFC-Specification#53]
Proposal to change type from IFCPOSITIVELENGTHMEASURE into IFCNONNEGATIVELENGTHMEASURE. This would allow zero length segments for vertical and cant alignment as last alignment segment, not really required but in line with horizontal alignment attribute HorizontalLength

**Comment by SergejMuhic** [comment]
Resolved in #76
