### ISSUE TITLE
IFCGeomodel usage in IFC ver 4.3 file

### ISSUE THREAD

**Issue by kirillantonov2901** [bSI-InfraRoom/IFC-Specification#554]
I'm trying to convert geological model into several realizations in ifc 4.3 as geosurfaces and as GRID structure
Can you show me direction where to search or send an example of "IfcGeomodel" usage in IFC file?

**Comment by pjanck** [comment]
See my answer here: https://github.com/buildingSMART/Sample-Test-Files/issues/132
