### ISSUE TITLE
[IfcTunnel] IfcMapConversion wrong OnlyProjectedCRS rule

### ISSUE THREAD

**Issue by iegorychev** [bSI-InfraRoom/IFC-Specification#559]
IfcTunnel schema:
ENTITY IfcMapConversion;
... 
WHERE
  OnlyProjectedCRS : 'IFC4x3.IFCPROJECTEDCRS' IN TYPEOF(SELF\IfcCoordinateOperation.TargetCRS); - has IFC4x3 in schema name part

**Comment by SergejMuhic** [comment]
Mhm, acknowledged. Will fix. Should have used the sub schema here. Thanks.

EDIT: or not even that. IfcMapConversion and IfcProjectedCRS are in the same subschema.

**Comment by iegorychev** [comment]
> EDIT: or not even that. IfcMapConversion and IfcProjectedCRS are in the same subschema.

Will it finally become 'IFC4X4_AABBCCDD.IFCPROJECTEDCRS' IN in generated .exp file, and if not, then why?
TYPEOF returns in 'SCHEMA.ENTITY' format, and IN checks presence of exact line here, but not a substring.

**Comment by SergejMuhic** [comment]
Yes, exactly. It will serialize in the exp file as 'IFC4X4_AABBCCDD.IFCPROJECTEDCRS'.

**Comment by SergejMuhic** [comment]
Beautiful:
![image](https://user-images.githubusercontent.com/16683597/229613052-8e2fd7a6-2c1d-4e80-b74e-9bd849006d4c.png)

Thanks for the support.
