### ISSUE TITLE
IfcSine attribute ConstantTerm

### ISSUE THREAD

**Issue by peterrdf** [bSI-InfraRoom/IFC-Specification#56]
I would propose to add a ConstantTerm to IfcSine or type IfcReal.

The reason is that in case a IfcAlignmentHorizontalSegment has a PredefinedType SINECURVE and both StartRadiusOfCurvature and EndRadiusOfCurvature are non-zero (but have the same sign) the generic IfcSine instance requires a ConstantTerm to be able to use as BaseCurve/ParentCurve for IfcCurveSegment.

**Comment by SergejMuhic** [comment]
Resolved in #76
