### ISSUE TITLE
Address the '{ .extDef}' tokens

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#58]
Parts of the documentation are marked with this '{ .extDef}'. It is not clear how these should be treated.

**Comment by TLiebich** [comment]
The {.extDef} token marks a text as being a quote from another source (mostly used for quoting other standards, like ISO 10303-42). It can then be rendered using a particular style (actually it is a grey text - but we could also change it to italics, having an intend, etc.). So I would argue to maintain it to mark quotes.

(PS: unsure what the best way is to handle it in markdown)

**Comment by SergejMuhic** [comment]
Alright, we can address this in the documentation generation.

**Comment by SergejMuhic** [comment]
Resolution for { extDef.}
https://github.com/bSI-InfraRoom/IFC-Specification/pull/81#discussion_r663161461
