### ISSUE TITLE
CT Earthworks Cuttings => CT Excavation Cuttings or separate CTs?

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#647]
The [Earthworks Cuttings](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/earthworks-cuttings.htm) CT exists in 4.3.
For IFC Tunnel, we added [IfcExcavation](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcexcavation.htm) as a supertype when we also added [IfcUndergroundExcavation](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcundergroundexcavation.htm) as a sibling to the [IfcEarthworksCut](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcearthworkscut.htm).

We need to decide on one of the below alternatives:
- Create a separate CT Underground Excavation Cuttings? Do we need the "FillsVoids" stuff also for underground excavation?
- Generalize CT Earthworks Cuttings to CT Excavation Cuttings?

Furthermore, CT Earthworks Cuttings states "represent a voiding of an existing or constructed Earthen element (referred to as the voided element) usually represented by a subtype of [IfcGeotechnicalElement](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/schema/ifcsharedinfrastructureelements/lexical/ifcgeotechnicalelement.htm)". For tunneling, we now have [IfcGeoScienceModel](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcgeosciencemodel.htm).

**Comment by pjanck** [comment]
> Generalize CT Earthworks Cuttings to CT Excavation Cuttings

+1 from me. 

Regarding rewording: I believe that the full text of the documentation should be revised.
