### ISSUE TITLE
Relationship between `IfcGeomodel` and `IfcGeoScienceModel`

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#650]
Today a question arose from the deployment support calls:

> If and how are `IfcGeomodel` and `IfcGeoScienceModel` connected in the data model?

@Michel-Rives @JanErikHoel @AdamMackellar12d @LeeGregory12d

**Comment by SergejMuhic** [comment]
Closing with this comment:
https://github.com/bSI-InfraRoom/IFC-Specification/issues/371#issuecomment-1120723814
