### ISSUE TITLE
Some DocLocalization misses Name

### ISSUE THREAD

**Issue by czapplitec** [bSI-InfraRoom/IFC-Specification#66]
It seems that in the latest a few commits, some DocLocalization miss Name, causing exceptions in the process to generate HTML. One example:

https://github.com/bSI-InfraRoom/IFC-Specification/blob/3eebad73c36d520d8f2794613842317cb0367ed6/IFC4x3/PropertyConstants/b/BOTH_3sytttEkrC8OE_plAGIwDS.xml#L1-L8

**Comment by SergejMuhic** [comment]
Indeed, built in a check into IfcDoc to assign an empty string if missing.

**Comment by czapplitec** [comment]
> Indeed, built in a check into IfcDoc to assign an empty string if missing.

Is this fix uploaded somewhere?

**Comment by SergejMuhic** [comment]
> 
> 
> > Indeed, built in a check into IfcDoc to assign an empty string if missing.
> 
> Is this fix uploaded somewhere?

I have uploaded it into a PR here https://github.com/buildingSMART/IfcDoc/pull/79/commits/7364a1aab5b3eb90cae1fe8f5d5654936cf8f936

Let me see if I can cherry-pick it directly into development.

**Comment by SergejMuhic** [comment]
Nah, that did not work. I have pushed directly to development. You can pull the change there.
