### ISSUE TITLE
File submission empty?

### ISSUE THREAD

**Issue by Artemis-kc** [bSI-InfraRoom/IFC-Specification#667]
@pjanck I was recently informed that in the last submission, it appeared that there was no file(?), 
But when I submitted the file from my side in GitHub, it passed the checker  (all green) and didn't get any comment even in the afternoon meeting. Can we please take a look at it? perhaps take it into a short meeting?

**Comment by pjanck** [comment]
Hi @Artemis-kc : yes, of course! Let's have a short call - I'll contact you through not so public means!
