### ISSUE TITLE
IFC4X4 typos found

### ISSUE THREAD

**Issue by iegorychev** [bSI-InfraRoom/IFC-Specification#679]
1. IfcAlignment only WR has incorrect function name:
ENTITY IfcAlignment
 SUBTYPE OF (IfcLinearPositioningElement);
	PredefinedType : OPTIONAL IfcAlignmentTypeEnum;
 WHERE
	AlignmentRepresentation : IfcAlignmenRepresentation(SELF); <-- Should be IfcAlignmentRepresentation

2. One of FUNCTION IfcAlignmentRepresentation return statements looks incorrect:

RETURN(SIZEOF(CurveThreeD) = 1 AND SIZEOF(CurveTwoD) = 1 AND CurveThreeD\IfcGradientCurve.BaseCurve :=: CurveTwoD);

to be more precise:
325 term = factor { multiplication_like_op factor } .
217 factor = simple_factor [ ’**’ simple_factor ] .
306 simple_factor = aggregate_initializer | entity_constructor | enumeration_reference | interval | query_expression | ( [ unary_op ] ( ’(’ expression ’)’ | primary ) ) .

As underlying expressions are not in parentheses (which are precisely define expression here), parser goes into primary and finds function call and then can't resolve ' = 1' which means an expression actually:
269 primary = literal | ( qualifiable_factor { qualifier } ) .
274 qualifiable_factor = attribute_ref | constant_factor | function_call | general_ref | population .

So should be:
RETURN((SIZEOF(CurveThreeD) = 1) AND (SIZEOF(CurveTwoD) = 1) AND (CurveThreeD\IfcGradientCurve.BaseCurve :=: CurveTwoD));

Regards,
Igor E.

**Comment by SergejMuhic** [comment]
Indeed, despite an operator precedence table that would not necessarily require parenthesis the grammar is clear on this and the parenthesis should be added.

Just FYI, the toolkit at disposal for IFC Tunnel Deployment generates the function correctly based on the precedence table.

We have to fix this nevertheless.

Thanks for the review.
