### ISSUE TITLE
Add IfcArithmeticOperatorEnum.MODULO

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#680]
See https://github.com/buildingSMART/IFC4.3.x-development/pull/689

**Comment by SergejMuhic** [comment]
This should be the baseline:
https://github.com/buildingSMART/IFC4.3.x-development/commit/f5320c189d6d58279d56387bfb7ccfd125be806c#diff-853b917da7b1ae274e92fe6e465650c13202c28e9b23a3dcbd723eaf3a052728
