### ISSUE TITLE
Change `IfcDoorTypeOperationEnum.REVOLVING` to `REVOLVING_HORIZONTAL`

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#682]
See https://github.com/buildingSMART/IFC4.3.x-development/issues/505

**Comment by SergejMuhic** [comment]
I do not see this change in the documentation. It says "reverted" in the provided link. If I remember correctly, I was reverting this once already.

ping @aothms @larswik @Michel-Rives @anborr

**Comment by SergejMuhic** [comment]
Closing and opening appropriate issue due to no engagement.
