### ISSUE TITLE
Add `IfcURIReference` to `IfcSimpleValue`

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#685]
See https://github.com/buildingSMART/IFC4.3.x-development/issues/546 and https://github.com/buildingSMART/IFC4.3.x-development/issues/604

**Comment by SergejMuhic** [comment]
The latest changes:
https://github.com/buildingSMART/IFC4.3.x-development/commit/0f0a89748d979952934a8bc63a2681293dea69bc
and
https://github.com/buildingSMART/IFC4.3.x-development/commit/c22af9524283ec303189955258ed61fcab201156
