### ISSUE TITLE
`IfcFooting.CorrectPredefinedType` missing parenthesis

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#691]
https://github.com/bSI-InfraRoom/IFC-Specification/blob/75858e216f0c7ff770a5e7e5fa1a4e1a07cde635/IFC4x3/Sections/Domain%20specific%20data%20schemas/Schemas/IfcStructuralElementsDomain/Entities/IfcFooting/DocEntity.xml#L19-L21

I think, there should be parenthesis around `EXISTS(...)`.

**Comment by SergejMuhic** [comment]
I would not agree here since a function call is an EXPRESS 'primary' and does not need parenthesis around it.
```
simple_factor = aggregate_initializer | entity_constructor | enumeration_reference | interval | query_expression | ( [ unary_op ] ( '(' expression ')' | primary ) ) .
```

I am a bit confused about this change in the bsi spec, ping @aothms @larswik @Michel-Rives @anborr @TLiebich . Why was this done?

**Comment by SergejMuhic** [comment]
Also closing, due to agreement to not focus on unnecessary changes.
