### ISSUE TITLE
status of IfcDirectrixDerivedReferenceSweptAreaSolid

### ISSUE THREAD

**Issue by TLiebich** [bSI-InfraRoom/IFC-Specification#71]
in latest specification it is shown as deprecated. However it was only added in IFC4x3_RC1 - which is not an official release of IFC. Therefore it should be removed. However the deprecated entity has a subtype IfcInclinedReferenceSweptAreaSolid. Is this supposed to remain, or can it be moved over into the subtype tree of IfcDirectrixCurveSweptAreaSolid?

Now, since IfcDirectrixCurveSweptAreaSolid can have a start and end param as length measure it looks like, that it would best be moved over.

N.B. there is no Documentation.md available for IfcDirectrixDerivedReferenceSweptAreaSolid

**Comment by SergejMuhic** [comment]
Resolved in #99
