### ISSUE TITLE
Split IfcImprovedGroundTypeEnum.GROUTED into INJECTIONGROUTED and JETGROUTED

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#722]
From the work with ground improvement Psets it became clear that these are two separate ways to perform ground improvement with different Psets applied.

**Comment by JontyDunn** [comment]
Hi Lars - jet grouting is acually a material replacement process, it's called jet grouting, but not really grouting... similar to deep mixing
