### ISSUE TITLE
Guided sweep usage for entities

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#730]
This is the resolution:
https://github.com/bSI-InfraRoom/IFC-Specification/issues/118#issuecomment-1155302267

The remaining task is to identify the entities on which the usage should be.

**Comment by larswik** [comment]
I would say that one is [IfcUndergroundExcavation](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcundergroundexcavation.htm). The RAR speaks about guide curves for sweeping, but I think that we need to ask the excavation, support & lining team about any additional usages for this type of geometry.

**Comment by pjanck** [comment]
Related concept template - bread crumbs: #648
