### ISSUE TITLE
Reconcile the IFC4.3_ADD2 changes for georeferencing into the Develop branch.

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#758]
Specify the necessary updates here:
- ...

See https://github.com/bSI-InfraRoom/IFC-Specification/pull/330 and compare with IFC4.3_ADD2.

**Comment by pjanck** [comment]
Related: #664 

EDIT: related as well: #687

**Comment by SergejMuhic** [comment]
I would propose (as we agreed) keeping our definition in the tunnel branch and creating a PR for the develop branch with the definitions of bSI. That way we can track our definition separately and propose it to bSI in our deliverable.

EDIT: if we want to keep the WKT reference optional we will need to make it a SET[0:1]
