### ISSUE TITLE
Correct IfcCurveDim

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#761]
bSI issue: https://github.com/buildingSMART/IFC4.3.x-development/issues/512

There was no engagement therefore it was not yet changed in our repo.

Remove check for `IfcCurveSegment2D`:
```
IF ('IFC4X3_X.IFCCURVESEGMENT2D' IN TYPEOF(Curve))
THEN RETURN(2);
```

**Comment by larswik** [comment]
Since the IfcCurveDim function in IFC4.3_ADD2 still includes the IfcCurveSegment2D check, should we do this change in our Tunnel branch (in the suggestion/proposal "bucket") from the IFC Tunnel project?

**Comment by SergejMuhic** [comment]
Yup certainly. That is the reason I posted. 😄
