### ISSUE TITLE
TestResult in Pset_InSituTestCommon

### ISSUE THREAD

**Issue by oyo-rdc** [bSI-InfraRoom/IFC-Specification#784]
Pset_InSituTestCommon currently has
- DepthRange
- TestMethod
- TestType

A property that holds the test result is missing. Can it be added? Or is there any place that can contain the test results?
If added, IfcPropertyListValue type to allow multiple values would be preferred. Can it allow both a list of numbers and a list of texts (not mixing them, of course)?

**Comment by SergejMuhic** [comment]
This should be it https://github.com/bSI-InfraRoom/IFC-Specification/pull/612

But it has not been merged yet. Awaiting some responses.

**Comment by oyo-rdc** [comment]
Is #612 about Pset_LabTestResult? This is about Pset_InSituTestCommon.

The name has "Common" at the end. Was the intention to keep a test result separately in another pset??
Several separate psets were proposed in this category (e.g. CPT, SPT, Pumping), and these tests have designated psets to hold the results. Wondering how other test results can be held. I suppose a user defined pset can do it, but would be more straightforward to have a property that holds the result in this pset.

**Comment by SergejMuhic** [comment]
Pset_InSituTestCommon properties are supposed to be properties relevant for all in situ test types. I am sorry, but I do not understand what kind of result would be expected that is be valid for all test types. Could you be more specific?

Typically, we go from explicit requirements. If there were no explicit requirements for generic tests, then there is no property to capture that. We could go back to the drawing board and decide on how such a generic result could look like. @Michel-Rives need some direction.

@larswik as I was not directly involved in the requirements of in situ test results I am lacking the background on where the results are. It seems quite logical that the results are the individual in situ test types as suggested by @oyo-rdc. Is this correct?

**Comment by larswik** [comment]
The Pset definitions are collected from the domain group specifications [here](https://app.box.com/file/1073785034660?s=jg3ys2w7t14se9wmpl6g82z51j28a7xw) - Line 175

However, looking at it closely, this looks more like a kind of supertype (i.e. properties part of all the specific tests).

**Comment by oyo-rdc** [comment]
Looking at the spreadsheet to which @larswik provided the link, I now recall the discussion that test specs and results are held in separate psets. Also, I found a pset that should be used for holding the test result - it is not yet in the document and I couldn't find it. So, never mind the issue I raised. Sorry for the confusion.
