### ISSUE TITLE
Usages for IfcLinearZone

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#798]
Shouldn't we have a usage (from IfcReferent-to IfcReferent) for [IfcLinearZone](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifclinearzone.htm). 
[Product Span Positioning](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/product-span-positioning.htm).

**Comment by SergejMuhic** [comment]
Yes, completely agree. Good catch there. We should probably go for a methodical review of all our added stuff and decide on case by case what is missing.
