### ISSUE TITLE
Typos in 4.7.2.1.8 Parabolic Transition Segment

### ISSUE THREAD

**Issue by RickBrice** [bSI-InfraRoom/IFC-Specification#90]
Suggest the following revisions to [4.7.2.1.8](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC3/HTML/link/parabolic-transition-segment.htm).

> The parabolic transition segment is modelled with IfcPolynomialCurve with certain restrictions. The size of the attribute CoefficientsY is restricted to 3. The quadratic term is on position 3. In general, the ~~CoefficietsX~~ Coefficie**n**tsX  size would be restricted to 2 and values specified as [0, 1]. This produces the following result:
> 
> y = ~~CoefficientsX[3]*x²~~ CoefficientsY[3]*x², where other values in CoefficientsY are 0.

The documentation says "CoefficietsX size would be restricted to 2 and values specified as [0, 1]" so CoefficientsX[3] would be undefined.

**Comment by SergejMuhic** [comment]
Will be addressed in the coming rail pull requests.
